// Config.swift - Auto-generated at build time
// Virtual read-only view of public environment variables available to Swift code.
//
// The string literals below are INTENTIONALLY EMPTY in source control —
// the real values are injected at iOS build time. Do not edit this file
// to add values, and do not inspect it to discover env values (you will
// only ever see ""). To find a value at agent-time, look up the env name
// in the project's .env file or in the Rork agent's environment listing.

import Foundation

enum Config {
    nonisolated static let allValues: [String: String] = [:]
}
