import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

test('public communities enforce membership, ownership, moderation, pagination and cleanup', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated;
      create table public.profiles(id text primary key,name text,handle text);
      create table public.test_blocks(first_id text,second_id text);
      create table public.test_mutes(viewer_id text,author_id text);
      create function public.user_id() returns text language sql stable as $$ select nullif(current_setting('test.user_id',true),'') $$;
      create function public.is_blocked_pair(a text,b text) returns boolean language sql stable as
        $$ select exists(select 1 from public.test_blocks where (first_id=a and second_id=b) or (first_id=b and second_id=a)) $$;
      create function public.can_view_account(a text,b text) returns boolean language sql stable as
        $$ select not public.is_blocked_pair(a,b) and not exists(select 1 from public.test_mutes where viewer_id=a and author_id=b) $$;
      insert into public.profiles values ('alice','Alice','alice'),('bob','Bob','bob'),('carol','Carol','carol');
    `);
    await db.exec(await readFile(new URL('../migrations/20261003020000_communities.sql',import.meta.url),'utf8'));
    const id='00000000-0000-4000-8000-000000000001';
    const postId='00000000-0000-4000-8000-000000000010';
    const secondPostId='00000000-0000-4000-8000-000000000011';
    const invoke=async (owner,op,{name='Friends',description='',member=null,post=null,body=''}={}) => (await db.query(
      'select public.manage_community($1,$2,$3::uuid,$4,$5,$6,$7::uuid,$8) as data',[owner,op,id,name,description,member,post,body])).rows[0].data;
    const read=async (date=null,cursor=null) => (await db.query('select public.get_community($1::uuid,$2::timestamptz,$3::uuid) as data',[id,date,cursor])).rows[0].data;
    const find=async (joined=false) => (await db.query("select public.find_communities('Friends',$1) as data",[joined])).rows[0].data;
    await db.exec("set test.user_id='alice'; set role anon;");
    const created=await invoke('alice','create');
    assert.equal(created.community.member_count,1); assert.equal(created.membership,'joined');
    assert.equal(created.role,'owner'); assert.equal(created.members[0].role,'owner');
    assert.equal((await invoke('alice','create')).community.member_count,1);
    await assert.rejects(invoke('alice','leave'),/Owner cannot leave/);
    await assert.rejects(invoke('alice','update',{name:' '}),/check constraint/);
    await assert.rejects(invoke('alice','update',{name:'\n\t'}),/check constraint/);
    await assert.rejects(invoke('alice','update',{description:'あ'.repeat(161)}),/check constraint/);
    await db.exec("set test.user_id='';");
    assert.equal((await read()).community.name,'Friends'); assert.equal((await find()).length,1);
    assert.deepEqual(await find(true),[]);
    await assert.rejects(invoke('alice','join'),/Login required/);
    for (const table of ['communities','community_members','community_posts']) await assert.rejects(db.query(`select * from public.${table}`),/permission denied/);
    await db.exec("set test.user_id='bob';");
    await assert.rejects(invoke('bob','create'),/Community ID already used/);
    await assert.rejects(invoke('alice','join'),/Login required/);
    await assert.rejects(invoke('bob','post',{post:postId,body:'Hello'}),/Join required/);
    await invoke('bob','join'); assert.equal((await invoke('bob','join')).community.member_count,2);
    assert.equal((await find(true)).length,1);
    await assert.rejects(invoke('bob','post',{post:postId,body:'😀'.repeat(71)}),/Invalid post/);
    await assert.rejects(invoke('bob','post',{post:postId,body:'\n\t'}),/Invalid post/);
    await invoke('bob','post',{post:postId,body:'Hello'});
    assert.equal((await invoke('bob','post',{post:postId,body:'Hello'})).posts.length,1);
    await assert.rejects(invoke('bob','post',{post:postId,body:'Different'}),/Post ID already used/);
    for (const op of ['update','delete','promote','demote']) await assert.rejects(invoke('bob',op,{member:'carol'}),/Owner required/);
    for (const op of ['remove','restore']) await assert.rejects(invoke('bob',op,{member:'carol'}),/Moderator required/);
    await db.exec("set test.user_id='carol';");
    await assert.rejects(invoke('carol','delete_post',{post:postId}),/Author or moderator required/);
    await db.exec("reset role; insert into public.test_mutes values('carol','bob'); set role anon;");
    assert.equal((await read()).posts.length,0);
    await db.exec("set test.user_id='alice';");
    await invoke('alice','promote',{member:'bob'});
    assert.equal((await read()).members.find(member=>member.id==='bob').role,'moderator');
    await db.exec("set test.user_id='bob';");
    assert.equal((await read()).role,'moderator');
    await assert.rejects(invoke('bob','update'),/Owner required/);
    await assert.rejects(invoke('bob','promote',{member:'carol'}),/Owner required/);
    await assert.rejects(invoke('bob','remove',{member:'alice'}),/Invalid member/);
    await db.exec("set test.user_id='carol';");
    await invoke('carol','join');
    await invoke('carol','post',{post:secondPostId,body:'Carol post'});
    await db.exec("set test.user_id='bob';");
    await invoke('bob','remove',{member:'carol'});
    assert.equal((await read()).members.find(member=>member.id==='carol').status,'removed');
    await invoke('bob','restore',{member:'carol'});
    await invoke('bob','delete_post',{post:secondPostId});
    assert.equal((await read()).posts.some(post=>post.id===secondPostId),false);
    await db.exec("set test.user_id='alice';");
    await invoke('alice','promote',{member:'carol'});
    await db.exec("set test.user_id='bob';");
    await assert.rejects(invoke('bob','remove',{member:'carol'}),/Owner required for moderator/);
    await db.exec("set test.user_id='alice';");
    await invoke('alice','demote',{member:'carol'});
    await invoke('alice','demote',{member:'bob'});
    await db.exec("set test.user_id='bob';");
    assert.equal((await read()).role,'member');
    await assert.rejects(invoke('bob','remove',{member:'carol'}),/Moderator required/);
    await db.exec("set test.user_id='alice';");
    await invoke('alice','promote',{member:'bob'});
    await invoke('alice','remove',{member:'bob'});
    await db.exec("reset role;");
    assert.deepEqual((await db.query("select status,role from public.community_members where community_id=$1::uuid and user_id='bob'",[id])).rows[0],{status:'removed',role:'member'});
    await db.exec("set test.user_id='bob'; set role anon;");
    assert.equal((await read()).membership,'removed'); assert.equal((await read()).role,null);
    await invoke('bob','leave'); // Cannot remove the moderation restriction through leave.
    await assert.rejects(invoke('bob','join'),/Membership removed/);
    await assert.rejects(invoke('bob','post',{post:postId,body:'Hello'}),/Join required/);
    await db.exec("set test.user_id='';"); assert.equal((await read()).members.some(member=>member.id==='bob'),false); // Removed users are not exposed to visitors.
    await db.exec("set test.user_id='alice';");
    await assert.rejects(invoke('alice','remove',{member:'alice'}),/Invalid member/);
    await invoke('alice','restore',{member:'bob'});
    await invoke('alice','delete_post',{post:postId});
    assert.equal((await read()).posts.length,0);
    await db.exec("reset role; insert into public.community_posts(id,community_id,user_id,body,created_at) select md5(n::text)::uuid,'"+id+"','alice','Post '||n,'2026-10-03'::timestamptz from generate_series(1,55) n; set role anon;");
    const first=await read(); assert.equal(first.posts.length,50); assert.equal(first.has_more,true);
    const cursor=first.posts.at(-1); const second=await read(cursor.created_at,cursor.id);
    assert.equal(second.posts.length,5); assert.equal(second.has_more,false);
    assert.equal(new Set([...first.posts,...second.posts].map(p=>p.id)).size,55);
    await assert.rejects(read(cursor.created_at),/Invalid cursor/);
    await db.exec("reset role; insert into public.test_blocks values('bob','alice'); set test.user_id='bob'; set role anon;");
    assert.equal(await read(),null); assert.deepEqual(await find(),[]);
    await assert.rejects(invoke('bob','post',{post:postId,body:'Blocked'}),/Blocked account/);
    await db.exec("reset role; delete from public.profiles where id='bob';");
    assert.equal((await db.query("select count(*)::int as count from public.community_members where user_id='bob'")).rows[0].count,0);
    await db.exec("delete from public.profiles where id='alice';");
    assert.equal((await db.query('select count(*)::int as count from public.communities')).rows[0].count,0);
    assert.equal((await db.query('select count(*)::int as count from public.community_posts')).rows[0].count,0);
  } finally { await db.close(); }
});
