import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case ja, en
    var id: String { rawValue }
    var title: String { self == .ja ? "日本語" : "English" }
    static var current: AppLanguage {
        AppLanguage(rawValue: UserDefaults.standard.string(forKey: "iruka-language") ?? "") ?? .ja
    }
    static var locale: Locale { Locale(identifier: current.rawValue) }
}

private let englishMessages: [String: String] = [
    "ブックマークはアカウントに保存され、端末間で共有されます。": "Bookmarks are saved to your account and synced across devices.",
    "開発モードのブックマークはこの端末に保存されます。": "Development bookmarks are saved on this device.",
    "ブックマーク": "Bookmarks",
    "ブックマークに追加": "Save bookmark",
    "ブックマークを解除": "Remove bookmark",
    "ブックマークするにはログインしてください。": "Sign in to save bookmarks.",
    "ブックマークを保存できませんでした。": "Couldn't save the bookmark.",
    "ブックマークを読み込めませんでした。": "Couldn't load bookmarks.",
    "まだブックマークがありません。": "No bookmarks yet.",
    "ブックマークはこの端末に保存されます。": "Bookmarks are saved on this device.",
    "ボトムバー": "Bottom bar",
    "ボトムバーの文字を表示": "Show bottom bar labels",
    "1人があなたの投稿にいいねしました。": "1 person liked your post.",
    "{count}人があなたの投稿にいいねしました。": "{count} people liked your post.",
    "{name}さんがいいねしました。": "{name} liked your post.",
    "返信": "Replies",
    "返信する": "Reply",
    "返信本文": "Reply text",
    "返信先": "Replying to",
    "返信先の投稿": "View parent post",
    "返信するにはログインしてください。": "Sign in to reply.",
    "返信を保存できませんでした。": "Couldn't save your reply.",
    "返信は1〜70文字で入力してください。": "Replies must contain 1–70 characters.",
    "まだ返信がありません。": "No replies yet.",
    "送信中…": "Sending…",
    "PDFとして出力": "Export as PDF",
    "PDFを作成できませんでした。": "Could not create the PDF.",
    "通知": "Notifications",
    "未読の通知": "Unread notifications",
    "自分の投稿へのいいねをお知らせします。": "Likes on your posts appear here.",
    "通知を見るにはログインしてください。": "Sign in to view notifications.",
    "開発モードでは通知は届きません。": "Notifications are unavailable in development mode.",
    "通知を読み込めませんでした。": "Couldn't load notifications.",
    "通知を既読にできませんでした。": "Couldn't mark notifications as read.",
    "すべて既読にする": "Mark all as read",
    "まだ通知がありません。": "No notifications yet.",
    "さんがあなたの投稿にいいねしました。": "liked your post.",
    "もっと見る": "Load more",
    "ホーム": "Home",
    "投稿": "Posts",
    "自分": "Mine",
    "設定": "Settings",
    "あなた": "You",
    "ログイン": "Sign in",
    "閉じる": "Close",
    "いいね": "Like",
    "ライト": "Light",
    "ダーク": "Dark",
    "ダークブルー": "Dark blue",
    "ミント": "Mint",
    "システム": "System",
    "ふぁぼ": "Favorite",
    "デフォルト": "Default",
    "高評価": "Thumbs up",
    "賛成": "Upvote",
    "外観": "Appearance",
    "テーマ": "Theme",
    "言語": "Language",
    "いいねアイコン": "Like icon",
    "アイコン": "Icon",
    "システムを選ぶと端末の外観設定に合わせて切り替わります。": "System follows your device appearance.",
    "いいねの表示に使うアイコンを選べます。": "Choose the icon used for likes.",
    "イルカ": "Iruka",
    "今の気持ちを、70字まで。": "Share how you feel, in up to 70 characters.",
    "新しい投稿": "New post",
    "投稿する": "Post",
    "投稿を作成": "Create a post",
    "投稿本文": "Post text",
    "メインナビゲーション": "Main navigation",
    "いまどうしてる？": "What's happening?",
    "プロフィール": "Profile",
    "今週の投稿": "Posts this week",
    "プロフィールを見る・編集": "View or edit profile",
    "自分の投稿": "My posts",
    "ログインすると、この端末を超えて自分の投稿が見られます。": "Sign in to access your posts across devices.",
    "まだ投稿がありません": "No posts yet",
    "まだ投稿がありません。": "No posts yet.",
    "70字以内で、いまの気持ちを残しましょう。": "Share how you feel in up to 70 characters.",
    "ログアウト": "Sign out",
    "ログアウトしますか？": "Sign out?",
    "この端末からサインアウトします。もう一度ログインできます。": "You will be signed out on this device. You can sign in again anytime.",
    "ゲストでログイン": "Continue as guest",
    "アカウント登録なしで試せます。データはこの端末にだけ保存され、30日で削除されます。": "Try it without an account. Data stays on this device only and is deleted after 30 days.",
    "ゲスト": "Guest",
    "ゲストモードでは通知は届きません。": "Notifications are unavailable in guest mode.",
    "ゲストモードのブックマークはこの端末に保存されます。": "Guest bookmarks are saved on this device.",
    "プロフィールを見る": "View profile",
    "投稿時刻": "Posted at",
    "文字数": "Characters",
    "いいねを取り消す": "Unlike",
    "いいね数": "Like count",
    "読み込み中…": "Loading…",
    "プロフィールを編集": "Edit profile",
    "プロフィール編集": "Edit profile",
    "プロフィールが見つかりません。": "Profile not found.",
    "再読み込み": "Try again",
    "プロフィールを読み込めませんでした。": "Couldn't load the profile.",
    "表示名（1〜40文字）": "Display name (1–40 characters)",
    "表示名": "Display name",
    "ユーザー名（英数字と_、3〜25文字）": "Username (letters, numbers and _, 3–25 characters)",
    "ユーザー名": "Username",
    "自己紹介（160文字まで）": "Bio (up to 160 characters)",
    "プロフィール画像URL": "Profile image URL",
    "HTTPSの画像URL。空欄にすると画像を解除します。": "HTTPS image URL. Leave blank to remove the image.",
    "キャンセル": "Cancel",
    "保存中…": "Saving…",
    "保存": "Save",
    "保存する": "Save",
    "保存できませんでした。入力内容とユーザー名の重複を確認してください。": "Couldn't save. Check your details and whether the username is available.",
    "ログインしてはじめる": "Sign in to get started",
    "GoogleかAppleで入ると、自分の投稿が残ります。": "Sign in with Google or Apple to save your posts.",
    "Googleで続ける": "Continue with Google",
    "Appleで続ける": "Continue with Apple",
    "開発用にログインをスキップ": "Skip sign-in for development",
    "スキップ中のデータはこの端末内に保存されます。": "Development data is saved on this device.",
    "ログインできませんでした": "Couldn't sign in",
    "ログインに失敗しました": "Sign-in failed",
    "ログイン用のURLが不正です": "The sign-in URL is invalid.",
    "認証コードを受け取れませんでした": "Couldn't receive the authorization code.",
    "URLが不正です": "The URL is invalid.",
    "ログインが時間切れになりました": "Sign-in timed out.",
    "ログインをキャンセルしました": "Sign-in was cancelled.",
    "いいねするにはAppleかGoogleでログインしてください。": "Sign in with Apple or Google to like posts.",
    "いいねを保存できませんでした。もう一度試してください。": "Couldn't save your like. Please try again.",
    "投稿またはいいねを読み込めませんでした。": "Couldn't load posts or likes.",
    "ユーザー": "User",
    "表示名・ユーザー名・自己紹介・画像URLを確認してください。": "Check your display name, username, bio and image URL.",
    "開発ユーザーが一致しません。": "Development user does not match.",
    "プロフィールを保存できませんでした。": "Couldn't save the profile.",
    "ログイン情報が見つかりません。もう一度試してください。": "Sign-in details are missing. Please try again.",
    "ポップアップがブロックされました。許可してからもう一度試してください。": "The pop-up was blocked. Allow pop-ups and try again.",
    "投稿は1〜70文字で入力してください。": "Posts must contain 1–70 characters.",
    "投稿できませんでした": "Couldn't post.",
    "投稿が見つかりません。": "Post not found.",
    "いいねするにはログインしてください。": "Sign in to like posts.",
    "いいねを保存できませんでした。": "Couldn't save your like.",
    "表示名は1〜40文字で入力してください。": "Display names must contain 1–40 characters.",
    "ユーザー名は小文字の英数字と_で3〜25文字にしてください。": "Usernames must contain 3–25 lowercase letters, numbers or underscores.",
    "自己紹介は160文字以内で入力してください。": "Bios must be 160 characters or fewer.",
    "画像にはHTTPSのURLを指定してください。": "Use an HTTPS URL for the image.",
    "画像のURLを確認してください。": "Check the image URL.",
    "このユーザー名は既に使われています。": "This username is already taken.",
    "プロフィールを保存できませんでした。もう一度試してください。": "Couldn't save the profile. Please try again.",
    "ログインしています…": "Signing in…",
    "ログイン中…": "Signing in…",
    "タイムラインを読み込めませんでした。": "Couldn't load the timeline.",
    "投稿できませんでした。もう一度試してください。": "Couldn't post. Please try again.",
    "投稿するには、GoogleかAppleで入ってください。": "Sign in with Google or Apple to post.",
    "開発モード・このブラウザに保存": "Development mode · saved in this browser",
    "編集する": "Edit",
    "1〜40文字": "1–40 characters",
    "小文字の英数字と_、3〜25文字": "Lowercase letters, numbers and _, 3–25 characters",
    "自己紹介": "Bio",
    "保存できませんでした。": "Couldn't save.",
    "戻る": "Back",
    "今朝": "Today",
    "昨日": "Yesterday",
    "Oops! Page not found": "Page not found.",
    "Return to Home": "Return to Home",
    "文字": "characters",
    "字": "characters",
    "投稿数": "Post count",
    " 投稿": " posts",
    "文字まで": "characters maximum",
    "開発セッションではありません。": "Not a development session.",
    "ミュート": "Mute",
    "ミュートを解除": "Unmute",
    "ブロック": "Block",
    "ブロックを解除": "Unblock",
    "ミュート中": "Muted accounts",
    "ブロック中": "Blocked accounts",
    "解除": "Remove",
    "設定を読み込めませんでした。": "Could not load your settings.",
    "設定を保存できませんでした。": "Could not save your settings.",
    "アカウント": "Account",
    "メールアドレス": "Email",
    "ログインしていません。": "You are not signed in.",
    "未設定": "Not set",
    "アカウントを削除": "Delete account",
    "アカウントを削除しますか？": "Delete this account?",
    "投稿、プロフィール、いいね、ブックマーク、通知が削除されます。この操作は取り消せません。": "Your posts, profile, likes, bookmarks, and notifications will be deleted. This cannot be undone.",
    "削除中…": "Deleting…",
    "削除する": "Delete",
    "アカウントを削除できませんでした。": "Couldn't delete the account.",
    "Today": "今日",
    "Yesterday": "昨日"
]
private let japaneseFormats: [String: String] = ["character_count": "%d字、上限%d字", "characters": "%d字", "like_count": "%d件", "post_count": "%d 投稿", "today_time": "今朝 %@", "yesterday_time": "昨日 %@"]
private let englishFormats: [String: String] = ["character_count": "%d characters, maximum %d", "characters": "%d characters", "like_count": "%d likes", "post_count": "%d posts", "today_time": "Today %@", "yesterday_time": "Yesterday %@"]

func L(_ message: String, _ arguments: CVarArg...) -> String {
    let language = AppLanguage.current
    let translated: String
    if let format = (language == .en ? englishFormats : japaneseFormats)[message] {
        translated = format
    } else if language == .en {
        if message.hasPrefix("ログインに失敗しました（") {
            translated = message.replacingOccurrences(of: "ログインに失敗しました（", with: "Sign-in failed (").replacingOccurrences(of: "）", with: ")")
        } else {
            translated = englishMessages[message] ?? message
        }
    } else {
        translated = message
    }
    return arguments.isEmpty ? translated : String(format: translated, locale: AppLanguage.locale, arguments: arguments)
}

struct AppLanguageModifier: ViewModifier {
    @AppStorage("iruka-language") private var language = AppLanguage.ja.rawValue
    func body(content: Content) -> some View {
        content.environment(\.locale, Locale(identifier: language == "en" ? "en" : "ja"))
    }
}

