import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case ja, en, ko
    case zhHans = "zh-CN"
    case zhHant = "zh-TW"
    var id: String { rawValue }
    var title: String {
        switch self {
        case .ja: "日本語"
        case .en: "English"
        case .ko: "한국어"
        case .zhHans: "简体中文"
        case .zhHant: "繁體中文"
        }
    }
    static var current: AppLanguage {
        AppLanguage(rawValue: UserDefaults.standard.string(forKey: "iruka-language") ?? "") ?? .ja
    }
    static var locale: Locale { Locale(identifier: current.rawValue) }
}

enum DateDisplayStyle: String, CaseIterable, Identifiable {
    case relative, short, full
    var id: String { rawValue }
    var label: String {
        switch self {
        case .relative: "相対表示"
        case .short: "月日と時刻"
        case .full: "年月日と時刻"
        }
    }
    static var current: DateDisplayStyle {
        DateDisplayStyle(rawValue: UserDefaults.standard.string(forKey: "iruka-date-display") ?? "") ?? .relative
    }
}

func formatDate(_ date: Date, includeTime: Bool = true) -> String {
    let calendar = Calendar.current
    let style = DateDisplayStyle.current
    if style == .relative {
        if calendar.isDateInToday(date) {
            return includeTime ? L("today_time", date.formatted(.dateTime.locale(AppLanguage.locale).hour().minute())) : L("今日")
        }
        if calendar.isDateInYesterday(date) {
            return includeTime ? L("yesterday_time", date.formatted(.dateTime.locale(AppLanguage.locale).hour().minute())) : L("昨日")
        }
    }
    var format = date.formatted(.dateTime.locale(AppLanguage.locale).month().day())
    if style == .full { format = date.formatted(.dateTime.locale(AppLanguage.locale).year().month().day()) }
    if includeTime { format += " " + date.formatted(.dateTime.locale(AppLanguage.locale).hour().minute()) }
    return format
}

private let englishMessages: [String: String] = [
    "スネーク": "Snake",
    "エサを集めて長くなり、壁や自分の体を避けましょう。": "Collect food to grow longer while avoiding walls and your own body.",

    "カラーペアパズル": "Color pair puzzle",
    "同じ色を4つ以上つなげて消す落ちものパズルです。": "A falling puzzle where four or more connected colors disappear.",
    "同じ色を4つ以上つなげると消えます。連鎖を狙いましょう。": "Connect four or more of the same color to clear them. Aim for chains.",
    "落ちものパズルの盤面": "Falling puzzle board",
    "赤": "Red",
    "青": "Blue",
    "緑": "Green",
    "黄": "Yellow",
    "次のペア": "Next pair",
    "連鎖": "Chain",
    "回転": "Rotate",
    "一気に落とす": "Hard drop",
    "落下": "Drop",
    "キーボードの矢印キーとスペースキーでも操作できます。": "You can also use the arrow keys and space bar.",
    "ピースを選んで盤面をタップ、またはドラッグして置きます。行か列を埋めると消えます。": "Select a piece, then tap or drag it onto the board. Filled rows or columns clear.",
    "ブロックパズル": "Block puzzle",
    "3つのピースを置き、行と列を消してスコアを伸ばすゲームです。": "Place three pieces, clear rows and columns, and build your score.",
    "ピースを選び、盤面の置きたい位置をタップ。行か列を埋めると消えます。": "Select a piece, then tap its top-left position on the board. Filled rows or columns clear.",
    "消したライン": "Lines cleared",
    "ブロックパズルの盤面": "Block puzzle board",
    "ピースを選択": "Choose a piece",
    "次のピース": "Next pieces",
    "ピース": "Piece",
    "使用済み": "Used",
    "ブロックあり": "Filled",
    "ここには置けません。": "This piece does not fit here.",
    "置ける場所がありません。ゲーム終了です。": "No pieces fit. Game over.",
    "囲碁": "Go",
    "石を取り、パスして終局する9路盤の囲碁です。": "Play 9x9 Go with captures and passing.",
    "9路盤で交互に打ちます。2回続けてパスすると終局です。": "Take turns on a 9x9 board. Two consecutive passes end the game.",
    "中国式の面積計算・白にコミ5.5目。死石は終局前に取り除いてください。": "Chinese area scoring with 5.5 komi for white. Capture dead stones before ending.",
    "囲碁盤": "Go board",
    "パス": "Pass",
    "相手がパスしました。続けてパスすると終局です。": "Your opponent passed. Passing now ends the game.",
    "オセロ": "Othello",
    "CPUまたは同じ端末で2人対戦できます。": "Play against the CPU or another person on this device.",
    "対戦モード": "Game mode",
    "2人で対戦": "Two players",
    "黒の石でCPUと対戦します。": "Play as black against the CPU.",
    "同じ端末で交互に遊べます。置ける場所を選んでください。": "Take turns on this device. Choose a highlighted square.",
    "黒": "Black",
    "白": "White",
    "の番": "'s turn",
    "の勝ち": " wins",
    "引き分け": "Draw",
    "は置けないためパスしました。": " has no legal move and passes.",
    "オセロの盤面": "Othello board",
    "行": " row, ",
    "列": " column",
    "置けます": "legal move",
    "空き": "empty",
    "新しい対局": "New game",
    "メニュー": "Menu",
    "メニューを開く": "Open menu",
    "メニューを閉じる": "Close menu",
    "ゲームセンター": "Game Center",
    "対局モード": "Game mode",
    "CPU対戦": "Play vs CPU",
    "部屋対局": "Room match",
    "あなたの手番": "Your side",
    "CPU": "CPU",
    "CPUが考えています…": "CPU is thinking…",
    "CPUの勝ち": "CPU wins",
    "CPUの番": "CPU's turn",
    "部屋キー": "Room key",
    "部屋キーを入力": "Enter a room key",
    "部屋キーをコピー": "Copy room key",
    "部屋キーをコピーしました。": "Room key copied.",
    "部屋キーのQRコード": "Room key QR code",
    "共有": "Share",
    "別の部屋に参加": "Join another room",
    "ログイン": "Sign in",
    "部屋を作成": "Create room",
    "部屋に参加": "Join room",
    "作成中…": "Creating…",
    "通信中…": "Connecting…",
    "招待URLのQRコード": "QR code for the invite link",
    "招待リンクをコピー": "Copy invite link",
    "招待リンクをコピーしました。": "Invite link copied.",
    "招待リンクをコピーできませんでした。": "Could not copy the invite link.",
    "オンライン対局にはログインが必要です。": "Sign in to play online.",
    "相手の参加を待っています。": "Waiting for an opponent to join.",
    "対局中です。相手の手を待っています。": "Match in progress. Waiting for the opponent's move.",
    "相手の番": "Opponent's turn",
    "あなたの番": "Your turn",
    "あなたの勝ち": "You win",
    "相手の勝ち": "Your opponent wins",
    "部屋キーを確認してください。": "Check the room key.",
    "対局部屋を作成できませんでした。もう一度お試しください。": "Could not create a room. Please try again.",
    "部屋が見つからないか、参加できませんでした。": "Room not found or could not be joined.",
    "この部屋は満員です。": "This room is full.",
    "部屋が見つからないか、有効期限が切れています。": "Room not found or has expired.",
    "相手が先に指しました。盤面を更新します。": "Your opponent moved first. Updating the board.",
    "手を保存できませんでした。盤面を更新して再度お試しください。": "Could not save the move. The board is updating; please try again.",
    "将棋": "Shogi",
    "先手": "Sente",
    "後手": "Gote",
    "先手の番": "Sente's turn",
    "後手の番": "Gote's turn",
    "先手の勝ち": "Sente wins",
    "後手の勝ち": "Gote wins",
    "持ち駒": "Pieces in hand",
    "王手": "Check",
    "将棋盤": "Shogi board",
    "空きマス": "Empty square",
    "成りを選択": "Promotion choice",
    "成りますか？": "Promote this piece?",
    "成る": "Promote",
    "成らない": "Keep unpromoted",
    "CPUまたはQRコード・部屋キーで招待した相手とオンライン対局できます。合法手・成り・持ち駒・王手と詰みを判定します。": "Play against the CPU or invite someone to an online match with a QR code or room key. Legal moves, promotion, drops, check, and checkmate are enforced.",
    "ゲームのスコアや対局結果を投稿で共有できます。": "Share game scores and match results in a post.",
    "目標": "Target",
    "目標を達成しました！": "Goal reached!",
    "ゲームを選択": "Choose a game",
    "神経衰弱": "Memory match",
    "ゲームのスコアや神経衰弱の手数を投稿で共有できます。": "Share your game scores and memory moves in a post.",
    "カードの中から同じ絵柄のペアを見つけましょう。": "Find all the matching pairs.",
    "矢印キーまたは画面のボタンで数字を合わせて2048を目指しましょう。": "Use arrow keys or the on-screen controls to combine tiles and reach 2048.",
    "矢印キーまたは画面のボタンで数字を合わせ、目標の数字を目指しましょう。": "Combine the numbered tiles to reach your selected target.",
    "新しいゲーム": "New game",
    "手数": "Moves",
    "経過時間": "Time",
    "秒": "s",
    "カード": "Card",
    "裏返し": "face down",
    "クリアしました！": "You cleared it!",
    "神経衰弱をクリアしました！": "I cleared Memory!",
    "ゲーム結果を投稿するにはログインしてください。": "Sign in to share your game result.",
    "ゲーム結果を投稿しました。": "Game result shared as a post.",
    "ゲーム結果を投稿できませんでした。": "Could not share the game result.",
    "ゲームオーバー": "Game over",
    "2048を達成しました！": "You reached 2048!",
    "スコア": "Score",
    "操作": "Controls",
    "上": "Up",
    "下": "Down",
    "左": "Left",
    "右": "Right",
    "神経衰弱や2048で遊び、記録を投稿で共有できます。": "Play Memory and 2048, then share your results in a post.",
    "神経衰弱や1024・2048・4096・8192・16384のパズル、将棋で遊び、記録を投稿で共有できます。": "Play Memory, number puzzles with goals from 1024 to 16384, or Shogi. Share your results in a post.",
    "神経衰弱、1024〜16384のパズル、CPU対戦やQRコード・部屋キーで招待した相手との将棋を楽しみ、記録を投稿で共有できます。": "Play Memory, number puzzles with targets from 1024 to 16384, and Shogi against the CPU or someone invited with a QR code or room key. Share your results in a post.",
    "ランキング": "Rankings",
    "結果共有数": "Result shares",
    "順位": "Rank",
    "投稿ランキングはいいね数を基準にしています。": "Posts are ranked by likes.",
    "ユーザーランキングは表示対象の投稿への合計いいね数を基準にしています。": "Users are ranked by total likes on visible posts.",
    "診断ランキングは診断結果を共有した投稿数を基準にしています。": "Quizzes are ranked by the number of result posts shared.",
    "投稿はいいね数、ユーザーは投稿への合計いいね数、診断は結果共有数を基準に順位を表示します。": "Posts rank by likes, users by total likes on their posts, and quizzes by result shares.",
    "ランキング対象の投稿がありません。": "No posts to rank.",
    "ランキング対象のユーザーがいません。": "No users to rank.",
    "ランキング対象の診断がありません。": "No quizzes to rank.",
  "診断": "Personality quiz", "診断を探す": "Discover quizzes", "診断を検索": "Search quizzes",
  "診断がありません。": "No quizzes yet.", "該当する診断がありません。": "No matching quizzes.", "診断を読み込めませんでした。": "Could not load quizzes.",
  "診断を作る": "Create a quiz", "診断を外す": "Remove quiz",
  "遊び・エンタメ用の診断です。医療や病気の判定には使わないでください。": "For entertainment only. Do not use this quiz to assess health or illness.",
  "診断タイトル": "Quiz title", "診断の説明（任意）": "Quiz description (optional)", "みんなで遊べる診断": "A quiz everyone can play",
  "診断結果": "Results", "結果を追加": "Add result", "結果名": "Result name", "結果を削除": "Remove result", "結果の説明": "Result description",
  "質問": "Question", "質問を追加": "Add question", "質問を削除": "Remove question", "回答の選択肢": "Answer option", "この回答が示す結果": "Result for this answer",
  "問": "questions", "あなたの診断結果": "Your result", "結果を共有するにはログインしてください。": "Sign in to share your result.",
  "診断結果を投稿しました。": "Your result was shared as a post.", "診断結果を投稿できませんでした。": "Could not share your result.",
  "投稿中…": "Sharing…", "結果を投稿で共有": "Share result as a post", "もう一度遊ぶ": "Play again",
  "この投稿者の結果": "This poster's result", "診断をやってみる": "Take this quiz",
  "オリジナルの診断を作って投稿し、ほかのユーザーは回答して結果をシェアしたり、診断結果の投稿から再度遊んだりできます。": "You can play quizzes from posts or find and play them in the quiz library. Search also finds quizzes, and you can share your result in a post.",
  "投票・クイズ": "Poll or quiz", "投稿形式": "Post format", "なし": "None", "投票": "Poll", "クイズ": "Quiz",
  "投稿に投票を付け、回答後に結果を確認できます。クイズでは複数の正解、正解・惜しい・不正解の判定、選択肢ごとのメッセージや解説を設定できます。": "Add polls to posts and view results after answering. Quizzes support multiple correct answers, correct/close/incorrect judgments, per-option messages, and an explanation.",
  "選択肢": "Option", "選択肢を削除": "Remove option", "判定": "Result", "正解": "Correct", "惜しい": "Close", "不正解": "Incorrect",
  "回答後のメッセージ（任意）": "Message after answering (optional)", "選択肢を追加": "Add option",
  "複数の選択肢を回答できるようにする": "Allow multiple selections", "回答後の解説（任意）": "Explanation after answering (optional)",
  "正解は複数設定できます。複数正解の場合は複数選択となり、判定は回答後に表示されます。": "You can set multiple correct answers. Multiple correct answers require multiple selections; results appear after you answer.",
  "回答後に投票結果を表示します。": "Poll results appear after an answer is submitted.", "回答": "responses",
  "回答するにはAppleかGoogleでログインしてください。": "Sign in with Apple or Google to answer.",
  "回答を保存できませんでした。": "Could not save your answer.", "回答を選択してください。": "Select an answer.",
  "回答を送信中…": "Submitting…", "回答する": "Submit answer", "解説": "Explanation",
  "複数選択できます。": "You can select multiple options.", "投票の入力内容を確認してください。": "Check the poll options and settings.",
  "投稿できませんでした。もう一度試してください。": "Could not publish the post. Please try again.",
  "おすすめ": "For you",
  "新着順": "Latest",
  "タイムラインの表示順": "Timeline order",
  "いいね・ブックマーク・自分の投稿を手がかりに、話題の近い投稿を優先します。": "Recommendations use topics from your likes, bookmarks, and posts.",
  "コミュニティ、メンバー情報、すべての投稿が削除されます。この操作は取り消せません。": "The community, memberships and all its posts will be deleted. This cannot be undone.",
  "コミュニティ": "Communities",
  "誰でも閲覧・参加できます。投稿するには参加が必要です。": "Anyone can view and join. Join to post.",
  "コミュニティを利用するにはAppleかGoogleでログインしてください。": "Sign in with Apple or Google to participate in communities.",
  "コミュニティを読み込めませんでした。": "Could not load the community.",
  "コミュニティの操作に失敗しました。再読み込みして参加状態を確認してください。": "Could not complete the action. Refresh to check your membership.",
  "コミュニティ名は1〜40文字、説明は160文字以内で入力してください。": "Community names must contain 1–40 characters and descriptions at most 160 characters.",
  "コミュニティを検索": "Search communities",
  "参加中のみ": "Joined communities only",
  "参加中": "Joined",
  "コミュニティを作成": "Create community",
  "コミュニティを編集": "Edit community",
  "コミュニティを削除": "Delete community",
  "コミュニティがありません。": "No communities found.",
  "コミュニティが見つかりません。": "Community not found.",
  "参加する": "Join",
  "退出する": "Leave",
  "参加が制限されています。管理者またはモデレーターに確認してください。": "Your membership is restricted. Contact the community owner or a moderator.",
  "管理者": "Owner",
  "モデレーター": "Moderator",
  "モデレーターにする": "Make moderator",
  "モデレーターを解除": "Remove moderator",
  "参加制限中": "Membership restricted",
  "参加を復帰": "Restore membership",
  "メンバーを除外": "Remove member",
  "コミュニティに投稿": "Post to community",
  "コミュニティの投稿": "Community posts",
  "固定された投稿": "Pinned post",
  "投稿を固定": "Pin post",
  "固定を解除": "Unpin post",
  "投稿を削除": "Delete post",
  "コミュニティ名（1〜40文字）": "Community name (1–40 characters)",
  "メンバーを除外しますか？": "Remove this member?",
  "投稿を削除しますか？": "Delete this post?",
  "コミュニティを削除しますか？": "Delete this community?",
  "管理者またはモデレーターが復帰させるまで、このメンバーは参加・投稿できなくなります。": "This member cannot join or post until an owner or moderator restores their membership.",
  "この操作は取り消せません。": "This action cannot be undone.",
  "実行する": "Confirm",
  "更新": "Refresh",

  "公開": "Public",
  "非公開": "Private",
  "公開リスト": "Public list",
  "リストを公開": "Publish list",
  "非公開にする": "Make private",
  "公開ページを見る": "View public page",
  "共有リンク": "Share link",
  "共有リンクをコピー": "Copy share link",
  "コピーしました": "Copied",
  "共有リンクをコピーできませんでした。": "Could not copy the share link.",
  "公開リストを探す": "Discover public lists",
  "リスト名で検索": "Search by list name",
  "公開リストがありません。": "No public lists found.",
  "公開リストを読み込めませんでした。": "Could not load the public list.",
  "このリストは公開されていないか、削除されています。": "This list is private or has been deleted.",
  "公開するにはAppleかGoogleでログインしてください。": "Sign in with Apple or Google to publish lists.",
  "リストは初期状態では非公開です。公開すると共有リンクから誰でも閲覧できます。": "Lists are private by default. Publishing lets anyone view them using the share link.",

  "リスト": "Lists",
  "リストを作成": "Create list",
  "リストを編集": "Edit list",
  "リストを削除": "Delete list",
  "リストを削除しますか？": "Delete this list?",
  "リストとメンバー設定が削除されます。投稿は削除されません。": "The list and its membership settings will be deleted. Posts will remain.",
  "リスト名（1〜40文字）": "List name (1–40 characters)",
  "説明（160文字まで）": "Description (up to 160 characters)",
  "メンバー": "Members",
  "メンバー一覧": "Member list",
  "ユーザーを検索": "Search users",
  "ユーザー名・表示名": "Username or display name",
  "追加": "Add",
  "リストから削除": "Remove from list",
  "リストの投稿": "List posts",
  "まだリストがありません。": "No lists yet.",
  "ユーザーを追加すると投稿が表示されます。": "Add users to see their posts.",
  "リストはこの端末に保存されます。": "Lists are saved on this device.",
  "リストは自分だけに表示され、端末間で共有されます。": "Lists are private to you and synced across devices.",
  "リストが見つかりません。": "List not found.",
  "リストを読み込めませんでした。": "Could not load lists.",
  "リストを保存できませんでした。": "Could not save the list.",
  "リストを保存・読み込みできませんでした。": "Could not save or load lists.",
  "ユーザーを検索できませんでした。": "Could not search users.",
  "ユーザーが見つかりません。": "User not found.",
  "リスト名は1〜40文字、説明は160文字以内で入力してください。": "List names must contain 1–40 characters and descriptions at most 160 characters.",

    "ブックマークはアカウントに保存され、端末間で共有されます。": "Bookmarks are saved to your account and synced across devices.",
    "開発モードのブックマークはこの端末に保存されます。": "Development bookmarks are saved on this device.",
    "ブックマーク": "Bookmarks",
    "ブックマークに追加": "Save bookmark",
    "ブックマークを解除": "Remove bookmark",
    "ブックマークするにはログインしてください。": "Sign in to save bookmarks.",
    "ブックマークを保存できませんでした。": "Couldn't save the bookmark.",
    "ブックマークを読み込めませんでした。": "Couldn't load bookmarks.",
    "まだブックマークがありません。": "No bookmarks yet.",
    "ブックマークはこの端末に保存されます。": "Bookmarks are saved on this device.",
    "ボトムバー": "Bottom bar",
    "ボトムバーの文字を表示": "Show bottom bar labels",
    "1人があなたの投稿にいいねしました。": "1 person liked your post.",
    "{count}人があなたの投稿にいいねしました。": "{count} people liked your post.",
    "{name}さんがいいねしました。": "{name} liked your post.",
    "返信": "Replies",
    "返信する": "Reply",
    "返信本文": "Reply text",
    "返信先": "Replying to",
    "返信先の投稿": "View parent post",
    "返信するにはログインしてください。": "Sign in to reply.",
    "返信を保存できませんでした。": "Couldn't save your reply.",
    "返信は1〜70文字で入力してください。": "Replies must contain 1–70 characters.",
    "まだ返信がありません。": "No replies yet.",
    "送信中…": "Sending…",
    "PDFとして出力": "Export as PDF",
    "PDFを作成できませんでした。": "Could not create the PDF.",
    "通知": "Notifications",
    "未読の通知": "Unread notifications",
    "自分の投稿へのいいねをお知らせします。": "Likes on your posts appear here.",
    "通知を見るにはログインしてください。": "Sign in to view notifications.",
    "開発モードでは通知は届きません。": "Notifications are unavailable in development mode.",
    "通知を読み込めませんでした。": "Couldn't load notifications.",
    "通知を既読にできませんでした。": "Couldn't mark notifications as read.",
    "すべて既読にする": "Mark all as read",
    "まだ通知がありません。": "No notifications yet.",
    "さんがあなたの投稿にいいねしました。": "liked your post.",
    "もっと見る": "Load more",
    "ホーム": "Home",
    "投稿": "Posts",
    "自分": "Mine",
    "設定": "Settings",
    "あなた": "You",
    "ログイン": "Sign in",
    "閉じる": "Close",
    "いいね": "Like",
    "ライト": "Light",
    "ダーク": "Dark",
    "ダークブルー": "Dark blue",
    "ミント": "Mint",
    "システム": "System",
    "ふぁぼ": "Favorite",
    "デフォルト": "Default",
    "高評価": "Thumbs up",
    "賛成": "Upvote",
    "外観": "Appearance",
    "テーマ": "Theme",
    "言語": "Language",
    "日付表示": "Date display",
    "相対表示": "Relative",
    "月日と時刻": "Month/day and time",
    "年月日と時刻": "Full date and time",
    "今日": "Today",
    "機能ガイド": "Feature guide",
    "Irukaの主要機能をまとめています。": "A quick guide to Iruka's main features.",
    "70文字までの投稿を作成し、返信・いいね・ブックマークを使えます。": "Create posts up to 70 characters, then reply, like, or bookmark them.",
    "公開コミュニティを作成・検索・参加できます。作成者とモデレーターはメンバーや投稿を管理し、投稿を固定できます。": "Create, search, and join public communities. Owners and moderators can manage members and posts and pin a post.",
    "ユーザーをリストに追加すると、そのユーザーの投稿をまとめて確認できます。公開すると共有リンクで誰でも閲覧できます。": "Add users to a list to see their posts together. Published lists can be viewed by anyone with the share link.",
    "自分の投稿へのいいね通知を確認し、既読にできます。": "Review likes on your posts and mark notifications as read.",
    "表示名、ユーザー名、自己紹介、プロフィール画像を編集できます。": "Edit your display name, username, bio, and profile image.",
    "テーマ、言語、いいねアイコン、日付表示などを変更できます。": "Change your theme, language, like icon, date display, and more.",
    "アカウントなしで試せます。データはこの端末に保存され、30日後に削除されます。": "Try Iruka without an account. Data is saved on this device and deleted after 30 days.",
    "ミュートしたアカウントを非表示にし、ブロックしたアカウントとの関係を制限できます。": "Hide muted accounts and restrict your interactions with blocked accounts.",
    "投稿詳細から投稿をPDFとして保存・共有できます。": "Save or share a post as a PDF from its detail view.",
    "設定からいつでもこのガイドを開けます。": "You can open this guide anytime from Settings.",
    "いいねアイコン": "Like icon",
    "アイコン": "Icon",
    "システムを選ぶと端末の外観設定に合わせて切り替わります。": "System follows your device appearance.",
    "いいねの表示に使うアイコンを選べます。": "Choose the icon used for likes.",
    "イルカ": "Iruka",
    "今の気持ちを、70字まで。": "Share how you feel, in up to 70 characters.",
    "新しい投稿": "New post",
    "画像を追加": "Add image",
    "画像を外す": "Remove image",
    "投稿の画像": "Post image",
    "投稿する": "Post",
    "投稿を作成": "Create a post",
    "投稿本文": "Post text",
    "メインナビゲーション": "Main navigation",
    "いまどうしてる？": "What's happening?",
    "プロフィール": "Profile",
    "今週の投稿": "Posts this week",
    "プロフィールを見る・編集": "View or edit profile",
    "自分の投稿": "My posts",
    "ログインすると、この端末を超えて自分の投稿が見られます。": "Sign in to access your posts across devices.",
    "まだ投稿がありません": "No posts yet",
    "まだ投稿がありません。": "No posts yet.",
    "70字以内で、いまの気持ちを残しましょう。": "Share how you feel in up to 70 characters.",
    "ログアウト": "Sign out",
    "ログアウトしますか？": "Sign out?",
    "この端末からサインアウトします。もう一度ログインできます。": "You will be signed out on this device. You can sign in again anytime.",
    "ゲストでログイン": "Continue as guest",
    "アカウント登録なしで試せます。データはこの端末にだけ保存され、30日で削除されます。": "Try it without an account. Data stays on this device only and is deleted after 30 days.",
    "ゲスト": "Guest",
    "ゲストモードでは通知は届きません。": "Notifications are unavailable in guest mode.",
    "ゲストモードのブックマークはこの端末に保存されます。": "Guest bookmarks are saved on this device.",
    "プロフィールを見る": "View profile",
    "投稿時刻": "Posted at",
    "文字数": "Characters",
    "いいねを取り消す": "Unlike",
    "リポスト": "Repost",
    "リポストを取り消す": "Undo repost",
    "引用": "Quote",
    "引用元の投稿は見つかりません": "The quoted post isn't available",
    "プロフィールを保存しました": "Profile saved",
    "このハンドルは使われています": "That handle is taken",
    "保存できませんでした。もう一度試してください。": "Couldn't save. Please try again.",
    "名前": "Name",
    "ハンドル": "Handle",
    "英小文字・数字・_ の3〜25文字": "3–25 characters: a–z, 0–9, _",
    "から利用": " joined",
    "いいね数": "Like count",
    "読み込み中…": "Loading…",
    "プロフィールを編集": "Edit profile",
    "プロフィール編集": "Edit profile",
    "プロフィールが見つかりません。": "Profile not found.",
    "再読み込み": "Try again",
    "プロフィールを読み込めませんでした。": "Couldn't load the profile.",
    "表示名（1〜40文字）": "Display name (1–40 characters)",
    "表示名": "Display name",
    "ユーザー名（英数字と_、3〜25文字）": "Username (letters, numbers and _, 3–25 characters)",
    "ユーザー名": "Username",
    "自己紹介（160文字まで）": "Bio (up to 160 characters)",
    "プロフィール画像URL": "Profile image URL",
    "HTTPSの画像URL。空欄にすると画像を解除します。": "HTTPS image URL. Leave blank to remove the image.",
    "キャンセル": "Cancel",
    "保存中…": "Saving…",
    "保存": "Save",
    "保存する": "Save",
    "保存できませんでした。入力内容とユーザー名の重複を確認してください。": "Couldn't save. Check your details and whether the username is available.",
    "ログインしてはじめる": "Sign in to get started",
    "GoogleかAppleで入ると、自分の投稿が残ります。": "Sign in with Google or Apple to save your posts.",
    "Googleで続ける": "Continue with Google",
    "Appleで続ける": "Continue with Apple",
    "開発用にログインをスキップ": "Skip sign-in for development",
    "スキップ中のデータはこの端末内に保存されます。": "Development data is saved on this device.",
    "ログインできませんでした": "Couldn't sign in",
    "ログインに失敗しました": "Sign-in failed",
    "ログイン用のURLが不正です": "The sign-in URL is invalid.",
    "認証コードを受け取れませんでした": "Couldn't receive the authorization code.",
    "URLが不正です": "The URL is invalid.",
    "ログインが時間切れになりました": "Sign-in timed out.",
    "ログインをキャンセルしました": "Sign-in was cancelled.",
    "いいねするにはAppleかGoogleでログインしてください。": "Sign in with Apple or Google to like posts.",
    "いいねを保存できませんでした。もう一度試してください。": "Couldn't save your like. Please try again.",
    "投稿またはいいねを読み込めませんでした。": "Couldn't load posts or likes.",
    "ユーザー": "User",
    "表示名・ユーザー名・自己紹介・画像URLを確認してください。": "Check your display name, username, bio and image URL.",
    "開発ユーザーが一致しません。": "Development user does not match.",
    "プロフィールを保存できませんでした。": "Couldn't save the profile.",
    "ログイン情報が見つかりません。もう一度試してください。": "Sign-in details are missing. Please try again.",
    "ポップアップがブロックされました。許可してからもう一度試してください。": "The pop-up was blocked. Allow pop-ups and try again.",
    "投稿は1〜70文字で入力してください。": "Posts must contain 1–70 characters.",
    "投稿できませんでした": "Couldn't post.",
    "投稿が見つかりません。": "Post not found.",
    "いいねするにはログインしてください。": "Sign in to like posts.",
    "いいねを保存できませんでした。": "Couldn't save your like.",
    "表示名は1〜40文字で入力してください。": "Display names must contain 1–40 characters.",
    "ユーザー名は小文字の英数字と_で3〜25文字にしてください。": "Usernames must contain 3–25 lowercase letters, numbers or underscores.",
    "自己紹介は160文字以内で入力してください。": "Bios must be 160 characters or fewer.",
    "画像にはHTTPSのURLを指定してください。": "Use an HTTPS URL for the image.",
    "画像のURLを確認してください。": "Check the image URL.",
    "このユーザー名は既に使われています。": "This username is already taken.",
    "プロフィールを保存できませんでした。もう一度試してください。": "Couldn't save the profile. Please try again.",
    "ログインしています…": "Signing in…",
    "ログイン中…": "Signing in…",
    "タイムラインを読み込めませんでした。": "Couldn't load the timeline.",
    "投稿できませんでした。もう一度試してください。": "Couldn't post. Please try again.",
    "投稿するには、GoogleかAppleで入ってください。": "Sign in with Google or Apple to post.",
    "開発モード・このブラウザに保存": "Development mode · saved in this browser",
    "編集する": "Edit",
    "1〜40文字": "1–40 characters",
    "小文字の英数字と_、3〜25文字": "Lowercase letters, numbers and _, 3–25 characters",
    "自己紹介": "Bio",
    "保存できませんでした。": "Couldn't save.",
    "戻る": "Back",
    "今朝": "Today",
    "昨日": "Yesterday",
    "Oops! Page not found": "Page not found.",
    "Return to Home": "Return to Home",
    "文字": "characters",
    "字": "characters",
    "投稿数": "Post count",
    " 投稿": " posts",
    "文字まで": "characters maximum",
    "開発セッションではありません。": "Not a development session.",
    "ミュート": "Mute",
    "ミュートを解除": "Unmute",
    "ブロック": "Block",
    "ブロックを解除": "Unblock",
    "ミュート中": "Muted accounts",
    "ブロック中": "Blocked accounts",
    "解除": "Remove",
    "設定を読み込めませんでした。": "Could not load your settings.",
    "設定を保存できませんでした。": "Could not save your settings.",
    "アカウント": "Account",
    "メールアドレス": "Email",
    "ログインしていません。": "You are not signed in.",
    "未設定": "Not set",
    "アカウントを削除": "Delete account",
    "アカウントを削除しますか？": "Delete this account?",
    "投稿、プロフィール、いいね、ブックマーク、通知が削除されます。この操作は取り消せません。": "Your posts, profile, likes, bookmarks, and notifications will be deleted. This cannot be undone.",
    "削除中…": "Deleting…",
    "削除する": "Delete",
    "アカウントを削除できませんでした。": "Couldn't delete the account.",
    "Today": "今日",
    "Yesterday": "昨日"
]
private let koreanMessages: [String: String] = [
    "スネーク": "스네이크",
    "エサを集めて長くなり、壁や自分の体を避けましょう。": "먹이를 모아 길어지면서 벽과 자신의 몸을 피하세요.",

    "カラーペアパズル": "컬러 페어 퍼즐",
    "同じ色を4つ以上つなげて消す落ちものパズルです。": "같은 색 네 개 이상을 연결해 지우는 낙하 퍼즐입니다.",
    "同じ色を4つ以上つなげると消えます。連鎖を狙いましょう。": "같은 색 네 개 이상을 연결하면 사라집니다. 연쇄를 노려 보세요.",
    "落ちものパズルの盤面": "낙하 퍼즐 판",
    "赤": "빨강",
    "青": "파랑",
    "緑": "초록",
    "黄": "노랑",
    "次のペア": "다음 쌍",
    "連鎖": "연쇄",
    "回転": "회전",
    "一気に落とす": "바로 떨어뜨리기",
    "落下": "낙하",
    "キーボードの矢印キーとスペースキーでも操作できます。": "방향키와 스페이스 키로도 조작할 수 있습니다.",
    "ピースを選んで盤面をタップ、またはドラッグして置きます。行か列を埋めると消えます。": "조각을 선택한 뒤 보드를 탭하거나 드래그해서 놓으세요. 행이나 열을 채우면 사라집니다.",
    "ブロックパズル": "블록 퍼즐",
    "3つのピースを置き、行と列を消してスコアを伸ばすゲームです。": "세 조각을 놓아 행과 열을 지우고 점수를 올리세요.",
    "ピースを選び、盤面の置きたい位置をタップ。行か列を埋めると消えます。": "조각을 선택하고 보드의 왼쪽 위 위치를 탭하세요. 행이나 열을 채우면 사라집니다.",
    "消したライン": "지운 줄",
    "ブロックパズルの盤面": "블록 퍼즐 판",
    "ピースを選択": "조각 선택",
    "次のピース": "다음 조각",
    "ピース": "조각",
    "使用済み": "사용함",
    "ブロックあり": "채워짐",
    "ここには置けません。": "여기에는 놓을 수 없습니다.",
    "置ける場所がありません。ゲーム終了です。": "놓을 곳이 없습니다. 게임 종료.",
    "囲碁": "바둑",
    "石を取り、パスして終局する9路盤の囲碁です。": "돌을 잡고 패스하여 끝내는 9줄 바둑입니다.",
    "9路盤で交互に打ちます。2回続けてパスすると終局です。": "9줄 바둑판에서 번갈아 둡니다. 연속 두 번 패스하면 종료됩니다.",
    "中国式の面積計算・白にコミ5.5目。死石は終局前に取り除いてください。": "중국식 면적 계산, 백 덤 5.5집. 끝내기 전에 죽은 돌을 잡아 주세요.",
    "囲碁盤": "바둑판",
    "パス": "패스",
    "相手がパスしました。続けてパスすると終局です。": "상대가 패스했습니다. 이제 패스하면 종료됩니다.",
    "オセロ": "오델로",
    "CPUまたは同じ端末で2人対戦できます。": "CPU 또는 같은 기기에서 2인 대전을 할 수 있습니다.",
    "対戦モード": "대전 모드",
    "2人で対戦": "2인 대전",
    "黒の石でCPUと対戦します。": "흑돌로 CPU와 대전합니다.",
    "同じ端末で交互に遊べます。置ける場所を選んでください。": "같은 기기에서 번갈아 플레이합니다. 놓을 수 있는 칸을 선택하세요.",
    "黒": "흑",
    "白": "백",
    "の番": " 차례",
    "の勝ち": " 승리",
    "引き分け": "무승부",
    "は置けないためパスしました。": "은(는) 둘 수 없어 패스했습니다.",
    "オセロの盤面": "오델로 판",
    "行": "행 ",
    "列": "열",
    "置けます": "놓을 수 있음",
    "空き": "빈 칸",
    "新しい対局": "새 대국",
    "メニュー": "메뉴",
    "メニューを開く": "메뉴 열기",
    "メニューを閉じる": "메뉴 닫기",
    "ゲームセンター": "게임 센터",
    "対局モード": "대국 모드",
    "CPU対戦": "CPU 대전",
    "部屋対局": "온라인 대국",
    "あなたの手番": "내 차례",
    "CPU": "CPU",
    "CPUが考えています…": "CPU가 생각 중입니다…",
    "CPUの勝ち": "CPU 승리",
    "CPUの番": "CPU 차례",
    "部屋キー": "방 코드",
    "部屋キーを入力": "방 코드 입력",
    "部屋キーをコピー": "방 코드 복사",
    "部屋キーをコピーしました。": "방 코드를 복사했습니다.",
    "部屋キーのQRコード": "방 코드 QR 코드",
    "共有": "공유",
    "別の部屋に参加": "다른 방 참가",
    "ログイン": "로그인",
    "部屋を作成": "방 만들기",
    "部屋に参加": "방 참가",
    "作成中…": "만드는 중…",
    "通信中…": "연결 중…",
    "招待URLのQRコード": "초대 링크 QR 코드",
    "招待リンクをコピー": "초대 링크 복사",
    "招待リンクをコピーしました。": "초대 링크를 복사했습니다.",
    "招待リンクをコピーできませんでした。": "초대 링크를 복사하지 못했습니다.",
    "オンライン対局にはログインが必要です。": "온라인 대전을 하려면 로그인하세요.",
    "相手の参加を待っています。": "상대방의 참가를 기다리는 중입니다.",
    "対局中です。相手の手を待っています。": "대국 중입니다. 상대의 수를 기다리는 중입니다.",
    "相手の番": "상대 차례",
    "あなたの番": "내 차례",
    "あなたの勝ち": "내 승리",
    "相手の勝ち": "상대 승리",
    "部屋キーを確認してください。": "방 코드를 확인하세요.",
    "対局部屋を作成できませんでした。もう一度お試しください。": "대국방을 만들지 못했습니다. 다시 시도하세요.",
    "部屋が見つからないか、参加できませんでした。": "방을 찾을 수 없거나 참가하지 못했습니다.",
    "この部屋は満員です。": "방이 가득 찼습니다.",
    "部屋が見つからないか、有効期限が切れています。": "방을 찾을 수 없거나 만료되었습니다.",
    "相手が先に指しました。盤面を更新します。": "상대가 먼저 두었습니다. 판을 업데이트합니다.",
    "手を保存できませんでした。盤面を更新して再度お試しください。": "수를 저장하지 못했습니다. 판을 업데이트한 뒤 다시 시도하세요.",
    "将棋": "쇼기",
    "先手": "선수",
    "後手": "후수",
    "先手の番": "선수 차례",
    "後手の番": "후수 차례",
    "先手の勝ち": "선수 승리",
    "後手の勝ち": "후수 승리",
    "持ち駒": "손에 든 말",
    "王手": "장군",
    "将棋盤": "쇼기판",
    "空きマス": "빈 칸",
    "成りを選択": "승격 선택",
    "成りますか？": "승격할까요?",
    "成る": "승격",
    "成らない": "승격하지 않음",
    "CPUまたはQRコード・部屋キーで招待した相手とオンライン対局できます。合法手・成り・持ち駒・王手と詰みを判定します。": "CPU와 대전하거나 QR 코드 또는 방 코드로 초대한 상대와 온라인 대국을 할 수 있습니다. 합법적인 이동, 승격, 말을 놓는 수, 장군과 체크메이트를 판정합니다.",
    "ゲームのスコアや対局結果を投稿で共有できます。": "게임 점수와 대국 결과를 게시물로 공유할 수 있습니다.",
    "目標": "목표",
    "目標を達成しました！": "목표 달성!",
    "ゲームを選択": "게임 선택",
    "神経衰弱": "같은 그림 찾기",
    "ゲームのスコアや神経衰弱の手数を投稿で共有できます。": "게임 점수와 같은 그림 찾기 횟수를 게시물로 공유할 수 있습니다.",
    "カードの中から同じ絵柄のペアを見つけましょう。": "같은 그림의 카드 짝을 모두 찾아보세요.",
    "矢印キーまたは画面のボタンで数字を合わせて2048を目指しましょう。": "방향키나 화면 버튼으로 같은 숫자를 합쳐 2048을 만들어 보세요.",
    "矢印キーまたは画面のボタンで数字を合わせ、目標の数字を目指しましょう。": "방향키나 화면 버튼으로 숫자 타일을 합쳐 선택한 목표에 도달해 보세요.",
    "新しいゲーム": "새 게임",
    "手数": "이동 횟수",
    "経過時間": "경과 시간",
    "秒": "초",
    "カード": "카드",
    "裏返し": "뒤집힘",
    "クリアしました！": "클리어했습니다!",
    "神経衰弱をクリアしました！": "같은 그림 찾기를 완료했어요!",
    "ゲーム結果を投稿するにはログインしてください。": "게임 결과를 공유하려면 로그인하세요.",
    "ゲーム結果を投稿しました。": "게임 결과를 게시물로 공유했습니다.",
    "ゲーム結果を投稿できませんでした。": "게임 결과를 공유하지 못했습니다.",
    "ゲームオーバー": "게임 종료",
    "2048を達成しました！": "2048을 만들었습니다!",
    "スコア": "점수",
    "操作": "조작",
    "上": "위",
    "下": "아래",
    "左": "왼쪽",
    "右": "오른쪽",
    "神経衰弱や2048で遊び、記録を投稿で共有できます。": "같은 그림 찾기와 2048을 플레이하고 결과를 게시물로 공유할 수 있습니다.",
    "神経衰弱や1024・2048・4096・8192・16384のパズル、将棋で遊び、記録を投稿で共有できます。": "같은 그림 찾기, 1024부터 16384까지 목표가 있는 숫자 퍼즐, 쇼기를 플레이하고 결과를 게시물로 공유할 수 있습니다.",
    "神経衰弱、1024〜16384のパズル、CPU対戦やQRコード・部屋キーで招待した相手との将棋を楽しみ、記録を投稿で共有できます。": "같은 그림 찾기, 1024~16384 숫자 퍼즐, CPU 대전이나 QR 코드 또는 방 코드로 초대한 상대와 쇼기를 즐기고 결과를 게시물로 공유할 수 있습니다.",
    "ランキング": "랭킹",
    "結果共有数": "결과 공유 수",
    "順位": "순위",
    "投稿ランキングはいいね数を基準にしています。": "게시물은 좋아요 수순으로 표시합니다.",
    "ユーザーランキングは表示対象の投稿への合計いいね数を基準にしています。": "사용자는 표시되는 게시물의 좋아요 합계순으로 표시합니다.",
    "診断ランキングは診断結果を共有した投稿数を基準にしています。": "진단은 결과 공유 게시물 수순으로 표시합니다.",
    "投稿はいいね数、ユーザーは投稿への合計いいね数、診断は結果共有数を基準に順位を表示します。": "게시물은 좋아요 수, 사용자는 게시물의 총 좋아요 수, 진단은 결과 공유 수를 기준으로 순위를 표시합니다.",
    "ランキング対象の投稿がありません。": "랭킹에 표시할 게시물이 없습니다.",
    "ランキング対象のユーザーがいません。": "랭킹에 표시할 사용자가 없습니다.",
    "ランキング対象の診断がありません。": "랭킹에 표시할 진단이 없습니다.",
  "診断": "성격 퀴즈", "診断を作る": "퀴즈 만들기", "診断を外す": "퀴즈 삭제",
  "遊び・エンタメ用の診断です。医療や病気の判定には使わないでください。": "재미를 위한 퀴즈입니다. 건강이나 질병을 판단하는 데 사용하지 마세요.",
  "診断タイトル": "퀴즈 제목", "診断の説明（任意）": "퀴즈 설명(선택)", "みんなで遊べる診断": "모두 함께 즐기는 퀴즈",
  "診断結果": "결과", "結果を追加": "결과 추가", "結果名": "결과 이름", "結果を削除": "결과 삭제", "結果の説明": "결과 설명",
  "質問": "질문", "質問を追加": "질문 추가", "質問を削除": "질문 삭제", "回答の選択肢": "답변 선택지", "この回答が示す結果": "이 답변이 가리키는 결과",
  "問": "문항", "あなたの診断結果": "내 결과", "結果を共有するにはログインしてください。": "결과를 공유하려면 로그인하세요.",
  "診断結果を投稿しました。": "결과를 게시물로 공유했습니다.", "診断結果を投稿できませんでした。": "결과를 게시물로 공유하지 못했습니다.",
  "投稿中…": "공유 중…", "結果を投稿で共有": "결과를 게시물로 공유", "もう一度遊ぶ": "다시 하기",
  "この投稿者の結果": "게시 작성자의 결과", "診断をやってみる": "퀴즈 참여하기",
  "診断を探す": "진단 찾기", "診断を検索": "진단 검색", "診断がありません。": "아직 진단이 없습니다.", "該当する診断がありません。": "검색 결과가 없습니다.", "診断を読み込めませんでした。": "진단을 불러오지 못했습니다.",
  "オリジナルの診断を作って投稿し、ほかのユーザーは回答して結果をシェアしたり、診断結果の投稿から再度遊んだりできます。": "게시물에서 진단에 참여하거나 진단 목록에서 찾아 바로 즐길 수 있습니다. 검색으로도 진단을 찾고 결과를 게시물로 공유할 수 있습니다.",
  "投票・クイズ": "투표 또는 퀴즈", "投稿形式": "게시물 형식", "なし": "없음", "投票": "투표", "クイズ": "퀴즈",
  "投稿に投票を付け、回答後に結果を確認できます。クイズでは複数の正解、正解・惜しい・不正解の判定、選択肢ごとのメッセージや解説を設定できます。": "게시물에 투표를 추가하고 답변 후 결과를 확인할 수 있습니다. 퀴즈에서는 여러 정답, 정답·아쉬움·오답 판정, 선택지별 메시지와 해설을 설정할 수 있습니다.",
  "選択肢": "선택지", "選択肢を削除": "선택지 삭제", "判定": "판정", "正解": "정답", "惜しい": "아쉬워요", "不正解": "오답",
  "回答後のメッセージ（任意）": "답변 후 메시지(선택)", "選択肢を追加": "선택지 추가",
  "複数の選択肢を回答できるようにする": "여러 선택지 허용", "回答後の解説（任意）": "답변 후 해설(선택)",
  "正解は複数設定できます。複数正解の場合は複数選択となり、判定は回答後に表示されます。": "정답을 여러 개 설정할 수 있습니다. 정답이 여러 개면 여러 항목을 선택해야 하며 답변 후 판정이 표시됩니다.",
  "回答後に投票結果を表示します。": "답변 후 투표 결과가 표시됩니다.", "回答": "응답",
  "回答するにはAppleかGoogleでログインしてください。": "답변하려면 Apple 또는 Google로 로그인하세요.",
  "回答を保存できませんでした。": "답변을 저장하지 못했습니다.", "回答を選択してください。": "답변을 선택하세요.",
  "回答を送信中…": "답변 전송 중…", "回答する": "답변하기", "解説": "해설",
  "複数選択できます。": "여러 항목을 선택할 수 있습니다.", "投票の入力内容を確認してください。": "투표 선택지와 설정을 확인하세요.",
  "投稿できませんでした。もう一度試してください。": "게시하지 못했습니다. 다시 시도하세요.",
  "おすすめ": "추천",
  "新着順": "최신순",
  "タイムラインの表示順": "타임라인 정렬",
  "いいね・ブックマーク・自分の投稿を手がかりに、話題の近い投稿を優先します。": "좋아요, 북마크, 내 게시물의 주제를 바탕으로 추천합니다.",
  "コミュニティ、メンバー情報、すべての投稿が削除されます。この操作は取り消せません。": "커뮤니티, 멤버 정보, 모든 게시물이 삭제됩니다. 이 작업은 되돌릴 수 없습니다.",
  "コミュニティ": "커뮤니티", "誰でも閲覧・参加できます。投稿するには参加が必要です。": "누구나 보고 참여할 수 있습니다. 게시하려면 먼저 참여하세요.",
  "コミュニティを利用するにはAppleかGoogleでログインしてください。": "커뮤니티를 이용하려면 Apple 또는 Google로 로그인하세요.",
  "コミュニティを読み込めませんでした。": "커뮤니티를 불러오지 못했습니다.", "コミュニティの操作に失敗しました。再読み込みして参加状態を確認してください。": "작업을 완료하지 못했습니다. 새로고침하여 참여 상태를 확인하세요.",
  "コミュニティ名は1〜40文字、説明は160文字以内で入力してください。": "커뮤니티 이름은 1~40자, 설명은 160자 이내로 입력하세요.", "コミュニティを検索": "커뮤니티 검색", "参加中のみ": "참여 중인 커뮤니티만", "参加中": "참여 중",
  "コミュニティを作成": "커뮤니티 만들기", "コミュニティを編集": "커뮤니티 수정", "コミュニティを削除": "커뮤니티 삭제", "コミュニティがありません。": "커뮤니티가 없습니다.", "コミュニティが見つかりません。": "커뮤니티를 찾을 수 없습니다.",
  "参加する": "참여하기", "退出する": "나가기", "参加が制限されています。管理者またはモデレーターに確認してください。": "참여가 제한되었습니다. 소유자 또는 운영자에게 문의하세요.",
  "管理者": "소유자", "モデレーター": "운영자", "モデレーターにする": "운영자로 지정", "モデレーターを解除": "운영자 해제", "参加制限中": "참여 제한됨", "参加を復帰": "참여 복원", "メンバーを除外": "멤버 내보내기",
  "コミュニティに投稿": "커뮤니티에 게시", "コミュニティの投稿": "커뮤니티 게시물", "固定された投稿": "고정된 게시물", "投稿を固定": "게시물 고정", "固定を解除": "고정 해제", "投稿を削除": "게시물 삭제",
  "コミュニティ名（1〜40文字）": "커뮤니티 이름(1~40자)", "メンバーを除外しますか？": "이 멤버를 내보낼까요?", "投稿を削除しますか？": "이 게시물을 삭제할까요?", "コミュニティを削除しますか？": "이 커뮤니티를 삭제할까요?",
  "管理者またはモデレーターが復帰させるまで、このメンバーは参加・投稿できなくなります。": "소유자나 운영자가 복원할 때까지 이 멤버는 참여하거나 게시할 수 없습니다.", "この操作は取り消せません。": "이 작업은 되돌릴 수 없습니다.", "実行する": "확인", "更新": "새로고침",
  "公開": "공개", "非公開": "비공개", "公開リスト": "공개 리스트", "リストを公開": "리스트 공개", "非公開にする": "비공개로 전환", "公開ページを見る": "공개 페이지 보기", "共有リンク": "공유 링크", "共有リンクをコピー": "공유 링크 복사", "コピーしました": "복사했습니다", "共有リンクをコピーできませんでした。": "공유 링크를 복사하지 못했습니다.",
  "公開リストを探す": "공개 리스트 찾기", "リスト名で検索": "리스트 이름 검색", "公開リストがありません。": "공개 리스트가 없습니다.", "公開リストを読み込めませんでした。": "공개 리스트를 불러오지 못했습니다.", "このリストは公開されていないか、削除されています。": "이 리스트는 비공개이거나 삭제되었습니다.", "公開するにはAppleかGoogleでログインしてください。": "리스트를 공개하려면 Apple 또는 Google로 로그인하세요.", "リストは初期状態では非公開です。公開すると共有リンクから誰でも閲覧できます。": "리스트는 기본적으로 비공개입니다. 공개하면 공유 링크를 통해 누구나 볼 수 있습니다.",
  "リスト": "리스트", "リストを作成": "리스트 만들기", "リストを編集": "리스트 수정", "リストを削除": "리스트 삭제", "リストを削除しますか？": "이 리스트를 삭제할까요?", "リストとメンバー設定が削除されます。投稿は削除されません。": "리스트와 멤버 설정이 삭제됩니다. 게시물은 삭제되지 않습니다.", "リスト名（1〜40文字）": "리스트 이름(1~40자)", "説明（160文字まで）": "설명(최대 160자)",
  "メンバー": "멤버", "メンバー一覧": "멤버 목록", "ユーザーを検索": "사용자 검색", "ユーザー名・表示名": "사용자 이름 또는 표시 이름", "追加": "추가", "リストから削除": "리스트에서 삭제", "リストの投稿": "리스트 게시물", "まだリストがありません。": "아직 리스트가 없습니다.", "ユーザーを追加すると投稿が表示されます。": "사용자를 추가하면 게시물이 표시됩니다.", "リストはこの端末に保存されます。": "리스트는 이 기기에 저장됩니다.", "リストは自分だけに表示され、端末間で共有されます。": "리스트는 나만 볼 수 있으며 기기 간에 동기화됩니다.", "リストが見つかりません。": "리스트를 찾을 수 없습니다.", "リストを読み込めませんでした。": "리스트를 불러오지 못했습니다.", "リストを保存できませんでした。": "리스트를 저장하지 못했습니다.", "リストを保存・読み込みできませんでした。": "리스트를 저장하거나 불러오지 못했습니다.", "ユーザーを検索できませんでした。": "사용자를 검색하지 못했습니다.", "ユーザーが見つかりません。": "사용자를 찾을 수 없습니다.", "リスト名は1〜40文字、説明は160文字以内で入力してください。": "리스트 이름은 1~40자, 설명은 160자 이내로 입력하세요.",
  "ミュート": "뮤트", "ミュートを解除": "뮤트 해제", "ミュート中": "뮤트 중", "ブロック": "차단", "ブロックを解除": "차단 해제", "ブロック中": "차단 중", "ミュート・ブロック中のアカウント": "뮤트 및 차단한 계정", "登録されたアカウントはありません。": "등록된 계정이 없습니다.", "解除": "해제", "設定を読み込めませんでした。": "설정을 불러오지 못했습니다.", "設定を保存できませんでした。": "설정을 저장하지 못했습니다.", "自分をミュート・ブロックできません。": "자신을 뮤트하거나 차단할 수 없습니다.",
  "PDFとして出力": "PDF로 내보내기", "PDFを開けませんでした。": "PDF 미리보기를 열 수 없습니다.", "PDFを作成できませんでした。": "PDF를 만들지 못했습니다.", "返信": "답글", "返信する": "답글 달기", "返信本文": "답글 내용", "返信先": "답글 대상", "返信先の投稿": "원본 게시물 보기", "返信するにはログインしてください。": "답글을 달려면 로그인하세요.", "返信を保存できませんでした。": "답글을 저장하지 못했습니다.", "返信は1〜70文字で入力してください。": "답글은 1~70자로 입력하세요.", "まだ返信がありません。": "아직 답글이 없습니다.", "送信中…": "전송 중…",
  "{name}さんがいいねしました。": "{name}님이 게시물을 좋아합니다.", "1人があなたの投稿にいいねしました。": "1명이 회원님의 게시물을 좋아합니다.", "{count}人があなたの投稿にいいねしました。": "{count}명이 회원님의 게시물을 좋아합니다.", "通知": "알림", "未読の通知": "읽지 않은 알림", "自分の投稿へのいいねをお知らせします。": "내 게시물에 대한 좋아요가 여기에 표시됩니다.", "通知を見るにはログインしてください。": "알림을 보려면 로그인하세요.", "開発モードでは通知は届きません。": "개발 모드에서는 알림을 받을 수 없습니다.", "通知を読み込めませんでした。": "알림을 불러오지 못했습니다.", "通知を既読にできませんでした。": "알림을 읽음으로 표시하지 못했습니다.", "すべて既読にする": "모두 읽음으로 표시", "まだ通知がありません。": "아직 알림이 없습니다.", "さんがあなたの投稿にいいねしました。": "님이 회원님의 게시물을 좋아합니다.", "もっと見る": "더 보기",
  "ブックマークはアカウントに保存され、端末間で共有されます。": "북마크는 계정에 저장되며 기기 간에 동기화됩니다.", "開発モードのブックマークはこの端末に保存されます。": "개발 모드의 북마크는 이 기기에 저장됩니다.", "ブックマーク": "북마크", "ブックマークに追加": "북마크 추가", "ブックマークを解除": "북마크 해제", "ブックマークするにはログインしてください。": "북마크하려면 로그인하세요.", "ブックマークを保存できませんでした。": "북마크를 저장하지 못했습니다.", "ブックマークを読み込めませんでした。": "북마크를 불러오지 못했습니다.", "まだブックマークがありません。": "아직 북마크가 없습니다.", "ブックマークはこの端末に保存されます。": "북마크는 이 기기에 저장됩니다.",
  "ナビゲーション": "탐색", "サイドナビゲーション": "사이드 탐색", "左側サイドバー（デスクトップ）": "왼쪽 사이드바(데스크톱)", "ボトムバー（デスクトップ）": "하단 바(데스크톱)", "デスクトップでは左側サイドバーを使用します。モバイルではボトムバーを使用します。": "데스크톱에서는 왼쪽 사이드바를 사용하고 모바일에서는 하단 바를 사용합니다.", "ボトムバー": "하단 바", "ボトムバーの文字を表示": "하단 바 레이블 표시", "ホーム": "홈", "検索": "검색", "キーワードで投稿を検索": "키워드로 게시물 검색", "ユーザー名や本文のキーワードで投稿を探せます。": "사용자 이름이나 게시물 키워드로 검색할 수 있습니다.", "該当する投稿がありません。": "검색 결과가 없습니다.", "投稿": "게시물", "自分": "내 활동", "設定": "설정", "あなた": "나", "あ": "나", "ログイン": "로그인", "閉じる": "닫기", "いいね": "좋아요", "ライト": "라이트", "ダーク": "다크", "ダークブルー": "다크 블루", "ミント": "민트", "システム": "시스템", "ふぁぼ": "즐겨찾기", "デフォルト": "기본값", "高評価": "추천", "賛成": "찬성", "外観": "모양", "テーマ": "테마", "言語": "언어", "いいねアイコン": "좋아요 아이콘", "アイコン": "아이콘", "システムを選ぶと端末の外観設定に合わせて切り替わります。": "시스템을 선택하면 기기의 모양 설정에 따라 전환됩니다.", "いいねの表示に使うアイコンを選べます。": "좋아요 표시 아이콘을 선택할 수 있습니다.", "イルカ": "돌고래",
  "今の気持ちを、70字まで。": "지금 기분을 70자 이내로 남겨보세요.", "新しい投稿": "새 게시물", "投稿する": "게시", "投稿を作成": "게시물 작성", "投稿本文": "게시물 내용", "メインナビゲーション": "주요 탐색", "いまどうしてる？": "지금 무슨 생각을 하고 있나요?", "プロフィール": "프로필", "今週の投稿": "이번 주 게시물", "プロフィールを見る・編集": "프로필 보기 및 수정", "自分の投稿": "내 게시물", "ログインすると、この端末を超えて自分の投稿が見られます。": "로그인하면 여러 기기에서 내 게시물을 볼 수 있습니다.", "まだ投稿がありません": "아직 게시물이 없습니다", "まだ投稿がありません。": "아직 게시물이 없습니다.", "70字以内で、いまの気持ちを残しましょう。": "지금 기분을 70자 이내로 남겨보세요.", "ログアウト": "로그아웃", "ログアウトしますか？": "로그아웃할까요?", "この端末からサインアウトします。もう一度ログインできます。": "이 기기에서 로그아웃합니다. 언제든 다시 로그인할 수 있습니다.", "ゲストでログイン": "게스트로 계속", "アカウント登録なしで試せます。データはこの端末にだけ保存され、30日で削除されます。": "계정 없이 사용해 보세요. 데이터는 이 기기에만 저장되며 30일 후 삭제됩니다.", "ゲスト": "게스트", "ゲストモード・このブラウザに保存": "게스트 모드 · 이 브라우저에 저장", "ゲストモードのブックマークはこの端末に保存されます。": "게스트 모드의 북마크는 이 기기에 저장됩니다.", "ゲストモードでは通知は届きません。": "게스트 모드에서는 알림을 받을 수 없습니다.", "ゲストの投稿を新しいアカウントに引き継ぎました": "게스트 게시물을 새 계정으로 옮겼습니다.", "ゲストのデータは保持期限（30日）を過ぎたため、削除されました。": "게스트 데이터는 30일 보관 기간이 지나 삭제되었습니다.", "プロフィールを見る": "프로필 보기", "投稿時刻": "게시 시간", "文字数": "글자 수", "いいねを取り消す": "좋아요 취소", "いいね数": "좋아요 수", "読み込み中…": "불러오는 중…", "プロフィールを編集": "프로필 수정", "プロフィール編集": "프로필 수정", "プロフィールが見つかりません。": "프로필을 찾을 수 없습니다.", "再読み込み": "다시 시도", "プロフィールを読み込めませんでした。": "프로필을 불러오지 못했습니다.", "表示名（1〜40文字）": "표시 이름(1~40자)", "表示名": "표시 이름", "ユーザー名（英数字と_、3〜25文字）": "사용자 이름(영문자, 숫자, _, 3~25자)", "ユーザー名": "사용자 이름", "自己紹介（160文字まで）": "소개(최대 160자)", "プロフィール画像URL": "프로필 이미지 URL", "プロフィール画像": "프로필 이미지", "画像を変更": "이미지 변경", "画像を削除": "이미지 삭제", "アップロード中…": "업로드 중…", "画像をアップロードできませんでした。": "이미지를 업로드하지 못했습니다.", "画像ファイルを選んでください。": "이미지 파일을 선택하세요.", "画像は10MBまでです。": "이미지는 최대 10MB까지 가능합니다.", "JPEGやPNGの画像を登録できます。": "JPEG 또는 PNG 이미지를 업로드할 수 있습니다.", "HTTPSの画像URL。空欄にすると画像を解除します。": "HTTPS 이미지 URL입니다. 비워 두면 이미지를 제거합니다.", "キャンセル": "취소", "保存中…": "저장 중…", "保存": "저장", "保存する": "저장", "保存できませんでした。入力内容とユーザー名の重複を確認してください。": "저장하지 못했습니다. 입력 내용과 사용자 이름 중복 여부를 확인하세요.", "ログインしてはじめる": "로그인하고 시작하기", "GoogleかAppleで入ると、自分の投稿が残ります。": "Google 또는 Apple로 로그인하면 게시물이 저장됩니다.", "Googleで続ける": "Google로 계속", "Appleで続ける": "Apple로 계속", "開発用にログインをスキップ": "개발용 로그인 건너뛰기", "スキップ中のデータはこの端末内に保存されます。": "개발 데이터는 이 기기에 저장됩니다.", "ログインできませんでした": "로그인하지 못했습니다", "ログインに失敗しました": "로그인에 실패했습니다", "ログイン用のURLが不正です": "로그인 URL이 올바르지 않습니다.", "認証コードを受け取れませんでした": "인증 코드를 받지 못했습니다.", "URLが不正です": "URL이 올바르지 않습니다.", "ログインが時間切れになりました": "로그인 시간이 초과되었습니다.", "ログインをキャンセルしました": "로그인을 취소했습니다.", "いいねするにはAppleかGoogleでログインしてください。": "좋아요를 누르려면 Apple 또는 Google로 로그인하세요.", "いいねを保存できませんでした。もう一度試してください。": "좋아요를 저장하지 못했습니다. 다시 시도하세요.", "投稿またはいいねを読み込めませんでした。": "게시물이나 좋아요를 불러오지 못했습니다.", "ユーザー": "사용자", "表示名・ユーザー名・自己紹介・画像URLを確認してください。": "표시 이름, 사용자 이름, 소개, 이미지 URL을 확인하세요.", "開発ユーザーが一致しません。": "개발 사용자 정보가 일치하지 않습니다.", "プロフィールを保存できませんでした。": "프로필을 저장하지 못했습니다.", "ログイン情報が見つかりません。もう一度試してください。": "로그인 정보를 찾을 수 없습니다. 다시 시도하세요.", "ポップアップがブロックされました。許可してからもう一度試してください。": "팝업이 차단되었습니다. 허용한 후 다시 시도하세요.", "投稿は1〜70文字で入力してください。": "게시물은 1~70자로 입력하세요.", "投稿できませんでした": "게시하지 못했습니다.", "投稿が見つかりません。": "게시물을 찾을 수 없습니다.", "いいねするにはログインしてください。": "좋아요를 누르려면 로그인하세요.", "いいねを保存できませんでした。": "좋아요를 저장하지 못했습니다.", "表示名は1〜40文字で入力してください。": "표시 이름은 1~40자로 입력하세요.", "ユーザー名は小文字の英数字と_で3〜25文字にしてください。": "사용자 이름은 소문자 영문자, 숫자, _로 3~25자여야 합니다.", "自己紹介は160文字以内で入力してください。": "소개는 160자 이내로 입력하세요.", "画像にはHTTPSのURLを指定してください。": "이미지에는 HTTPS URL을 사용하세요.", "画像のURLを確認してください。": "이미지 URL을 확인하세요.", "このユーザー名は既に使われています。": "이미 사용 중인 사용자 이름입니다.", "プロフィールを保存できませんでした。もう一度試してください。": "프로필을 저장하지 못했습니다. 다시 시도하세요.", "ログインしています…": "로그인 중…", "ログイン中…": "로그인 중…", "タイムラインを読み込めませんでした。": "타임라인을 불러오지 못했습니다.", "投稿できませんでした。もう一度試してください。": "게시하지 못했습니다. 다시 시도하세요.", "投稿するには、GoogleかAppleで入ってください。": "게시하려면 Google 또는 Apple로 로그인하세요.", "開発モード・このブラウザに保存": "개발 모드 · 이 브라우저에 저장", "編集する": "수정", "1〜40文字": "1~40자", "小文字の英数字と_、3〜25文字": "소문자 영문자, 숫자, _, 3~25자", "3〜25文字": "3~25자", "小文字の英数字と_": "소문자 영문자, 숫자, _", "確認中…": "확인 중…", "利用できるユーザー名です。": "사용할 수 있는 사용자 이름입니다.", "自己紹介": "소개", "保存できませんでした。": "저장하지 못했습니다.", "戻る": "뒤로", "今朝": "오늘", "昨日": "어제", "Oops! Page not found": "페이지를 찾을 수 없습니다.", "Return to Home": "홈으로 돌아가기", "文字": "자", "字": "자", "投稿数": "게시물 수", " 投稿": "개 게시물", "文字まで": "자까지", "開発セッションではありません。": "개발 세션이 아닙니다.", "アカウント": "계정", "メールアドレス": "이메일 주소", "ログインしていません。": "로그인되어 있지 않습니다.", "未設定": "설정되지 않음", "アカウントを削除": "계정 삭제", "アカウントを削除しますか？": "계정을 삭제할까요?", "投稿、プロフィール、いいね、ブックマーク、通知が削除されます。この操作は取り消せません。": "게시물, 프로필, 좋아요, 북마크, 알림이 삭제됩니다. 이 작업은 되돌릴 수 없습니다.", "削除中…": "삭제 중…", "削除する": "삭제", "アカウントを削除できませんでした。": "계정을 삭제하지 못했습니다.", "Today": "오늘", "Yesterday": "어제"
]
private let koreanExtraMessages: [String: String] = [
    "日付表示": "날짜 표시",
    "相対表示": "상대 표시",
    "月日と時刻": "월일 및 시간",
    "年月日と時刻": "전체 날짜 및 시간",
    "今日": "오늘",
    "機能ガイド": "기능 안내",
    "Irukaの主要機能をまとめています。": "Iruka의 주요 기능을 한눈에 확인할 수 있습니다.",
    "70文字までの投稿を作成し、返信・いいね・ブックマークを使えます。": "70자 이내의 게시물을 작성하고 답글, 좋아요, 북마크를 사용할 수 있습니다.",
    "公開コミュニティを作成・検索・参加できます。作成者とモデレーターはメンバーや投稿を管理し、投稿を固定できます。": "공개 커뮤니티를 만들고 검색하고 참여할 수 있습니다. 소유자와 운영자는 멤버와 게시물을 관리하고 게시물을 고정할 수 있습니다.",
    "ユーザーをリストに追加すると、そのユーザーの投稿をまとめて確認できます。公開すると共有リンクで誰でも閲覧できます。": "사용자를 리스트에 추가하면 게시물을 모아 볼 수 있습니다. 공개한 리스트는 공유 링크가 있는 누구나 볼 수 있습니다.",
    "自分の投稿へのいいね通知を確認し、既読にできます。": "내 게시물의 좋아요 알림을 확인하고 읽음으로 표시할 수 있습니다.",
    "表示名、ユーザー名、自己紹介、プロフィール画像を編集できます。": "표시 이름, 사용자 이름, 소개, 프로필 이미지를 수정할 수 있습니다.",
    "テーマ、言語、いいねアイコン、日付表示などを変更できます。": "테마, 언어, 좋아요 아이콘, 날짜 표시 등을 변경할 수 있습니다.",
    "アカウントなしで試せます。データはこの端末に保存され、30日後に削除されます。": "계정 없이 사용해 볼 수 있습니다. 데이터는 이 기기에 저장되며 30일 후 삭제됩니다.",
    "ミュートしたアカウントを非表示にし、ブロックしたアカウントとの関係を制限できます。": "뮤트한 계정을 숨기고 차단한 계정과의 상호작용을 제한할 수 있습니다.",
    "投稿詳細から投稿をPDFとして保存・共有できます。": "게시물 상세 화면에서 게시물을 PDF로 저장하거나 공유할 수 있습니다.",
    "設定からいつでもこのガイドを開けます。": "설정에서 언제든 이 안내를 열 수 있습니다.",
]
private let simplifiedChineseMessages: [String: String] = [
    "スネーク": "贪吃蛇",
    "エサを集めて長くなり、壁や自分の体を避けましょう。": "收集食物让身体变长，同时避开墙壁和自己的身体。",

    "カラーペアパズル": "彩色双球拼图",
    "同じ色を4つ以上つなげて消す落ちものパズルです。": "连接四个以上同色球即可消除的下落拼图。",
    "同じ色を4つ以上つなげると消えます。連鎖を狙いましょう。": "连接四个以上同色球即可消除，试着形成连锁。",
    "落ちものパズルの盤面": "下落拼图棋盘",
    "赤": "红",
    "青": "蓝",
    "緑": "绿",
    "黄": "黄",
    "次のペア": "下一对",
    "連鎖": "连锁",
    "回転": "旋转",
    "一気に落とす": "直接落下",
    "落下": "落下",
    "キーボードの矢印キーとスペースキーでも操作できます。": "也可以使用方向键和空格键操作。",
    "ピースを選んで盤面をタップ、またはドラッグして置きます。行か列を埋めると消えます。": "选择方块，然后点击或拖到棋盘上。填满行或列即可消除。",
    "ブロックパズル": "方块拼图",
    "3つのピースを置き、行と列を消してスコアを伸ばすゲームです。": "放置三个方块，消除整行或整列来提高分数。",
    "ピースを選び、盤面の置きたい位置をタップ。行か列を埋めると消えます。": "选择方块，然后点击棋盘上要放置的左上角。填满行或列即可消除。",
    "消したライン": "已消除行列",
    "ブロックパズルの盤面": "方块拼图棋盘",
    "ピースを選択": "选择方块",
    "次のピース": "接下来的方块",
    "ピース": "方块",
    "使用済み": "已使用",
    "ブロックあり": "已填充",
    "ここには置けません。": "无法放在这里。",
    "置ける場所がありません。ゲーム終了です。": "没有可放置的位置，游戏结束。",
    "囲碁": "围棋",
    "石を取り、パスして終局する9路盤の囲碁です。": "可提子并以停着结束的九路围棋。",
    "9路盤で交互に打ちます。2回続けてパスすると終局です。": "在九路棋盘上轮流落子。连续两次停着后终局。",
    "中国式の面積計算・白にコミ5.5目。死石は終局前に取り除いてください。": "采用中国规则数子，白棋贴目5.5。终局前请提掉死子。",
    "囲碁盤": "围棋棋盘",
    "パス": "停着",
    "相手がパスしました。続けてパスすると終局です。": "对方已停着。再次停着即终局。",
    "オセロ": "黑白棋",
    "CPUまたは同じ端末で2人対戦できます。": "可与 CPU 对战，也可在同一设备上双人对战。",
    "対戦モード": "对战模式",
    "2人で対戦": "双人对战",
    "黒の石でCPUと対戦します。": "执黑棋与 CPU 对战。",
    "同じ端末で交互に遊べます。置ける場所を選んでください。": "在同一设备上轮流落子。请选择可落子的位置。",
    "黒": "黑",
    "白": "白",
    "の番": "回合",
    "の勝ち": "获胜",
    "引き分け": "平局",
    "は置けないためパスしました。": "无棋可下，已跳过。",
    "オセロの盤面": "黑白棋棋盘",
    "行": "行",
    "列": "列",
    "置けます": "可落子",
    "空き": "空位",
    "新しい対局": "新对局",
    "メニュー": "菜单",
    "メニューを開く": "打开菜单",
    "メニューを閉じる": "关闭菜单",
    "ゲームセンター": "游戏中心",
    "対局モード": "对局模式",
    "CPU対戦": "与电脑对战",
    "部屋対局": "房间对局",
    "あなたの手番": "你的阵营",
    "CPU": "电脑",
    "CPUが考えています…": "电脑思考中…",
    "CPUの勝ち": "电脑获胜",
    "CPUの番": "电脑回合",
    "部屋キー": "房间码",
    "部屋キーを入力": "输入房间码",
    "部屋キーをコピー": "复制房间码",
    "部屋キーをコピーしました。": "已复制房间码。",
    "部屋キーのQRコード": "房间码二维码",
    "共有": "分享",
    "別の部屋に参加": "加入其他房间",
    "ログイン": "登录",
    "部屋を作成": "创建房间",
    "部屋に参加": "加入房间",
    "作成中…": "正在创建…",
    "通信中…": "连接中…",
    "招待URLのQRコード": "邀请链接二维码",
    "招待リンクをコピー": "复制邀请链接",
    "招待リンクをコピーしました。": "已复制邀请链接。",
    "招待リンクをコピーできませんでした。": "无法复制邀请链接。",
    "オンライン対局にはログインが必要です。": "请登录后进行在线对战。",
    "相手の参加を待っています。": "正在等待对手加入。",
    "対局中です。相手の手を待っています。": "对局进行中，正在等待对手落子。",
    "相手の番": "对手回合",
    "あなたの番": "你的回合",
    "あなたの勝ち": "你赢了",
    "相手の勝ち": "对手获胜",
    "部屋キーを確認してください。": "请检查房间码。",
    "対局部屋を作成できませんでした。もう一度お試しください。": "无法创建对局房间，请重试。",
    "部屋が見つからないか、参加できませんでした。": "找不到房间或无法加入。",
    "この部屋は満員です。": "房间已满。",
    "部屋が見つからないか、有効期限が切れています。": "找不到房间或房间已过期。",
    "相手が先に指しました。盤面を更新します。": "对手先走了一步，正在更新棋盘。",
    "手を保存できませんでした。盤面を更新して再度お試しください。": "无法保存这一步。棋盘正在更新，请重试。",
    "将棋": "日本将棋",
    "先手": "先手",
    "後手": "后手",
    "先手の番": "先手回合",
    "後手の番": "后手回合",
    "先手の勝ち": "先手获胜",
    "後手の勝ち": "后手获胜",
    "持ち駒": "手持棋子",
    "王手": "将军",
    "将棋盤": "将棋棋盘",
    "空きマス": "空格",
    "成りを選択": "选择升级",
    "成りますか？": "要升级棋子吗？",
    "成る": "升级",
    "成らない": "不升级",
    "CPUまたはQRコード・部屋キーで招待した相手とオンライン対局できます。合法手・成り・持ち駒・王手と詰みを判定します。": "可以与电脑对战，也可以通过二维码或房间码邀请对手在线对局。游戏会判定合法移动、升变、打入、将军和将死。",
    "ゲームのスコアや対局結果を投稿で共有できます。": "可以将游戏分数和对局结果分享到帖子。",
    "目標": "目标",
    "目標を達成しました！": "达成目标！",
    "ゲームを選択": "选择游戏",
    "神経衰弱": "记忆配对",
    "ゲームのスコアや神経衰弱の手数を投稿で共有できます。": "可以将游戏分数和配对步数分享到帖子。",
    "カードの中から同じ絵柄のペアを見つけましょう。": "找出所有相同图案的卡片。",
    "矢印キーまたは画面のボタンで数字を合わせて2048を目指しましょう。": "使用方向键或屏幕按钮合并数字，挑战2048。",
    "矢印キーまたは画面のボタンで数字を合わせ、目標の数字を目指しましょう。": "使用方向键或屏幕按钮合并数字，达到所选目标。",
    "新しいゲーム": "新游戏",
    "手数": "步数",
    "経過時間": "用时",
    "秒": "秒",
    "カード": "卡片",
    "裏返し": "背面朝上",
    "クリアしました！": "通关了！",
    "神経衰弱をクリアしました！": "我完成了记忆配对！",
    "ゲーム結果を投稿するにはログインしてください。": "请登录后分享游戏结果。",
    "ゲーム結果を投稿しました。": "已将游戏结果分享到帖子。",
    "ゲーム結果を投稿できませんでした。": "无法分享游戏结果。",
    "ゲームオーバー": "游戏结束",
    "2048を達成しました！": "达成2048了！",
    "スコア": "分数",
    "操作": "操作",
    "上": "上",
    "下": "下",
    "左": "左",
    "右": "右",
    "神経衰弱や2048で遊び、記録を投稿で共有できます。": "可以玩记忆配对和2048，并将成绩分享到帖子。",
    "神経衰弱や1024・2048・4096・8192・16384のパズル、将棋で遊び、記録を投稿で共有できます。": "可以玩记忆配对、目标从1024到16384的数字拼图或日本将棋，并将成绩分享到帖子。",
    "神経衰弱、1024〜16384のパズル、CPU対戦やQRコード・部屋キーで招待した相手との将棋を楽しみ、記録を投稿で共有できます。": "可以玩记忆配对、目标为1024至16384的数字拼图，以及与电脑对战或通过二维码、房间码邀请对手在线进行的日本将棋，并将成绩分享到帖子。",
    "ランキング": "排行榜",
    "結果共有数": "结果分享数",
    "順位": "排名",
    "投稿ランキングはいいね数を基準にしています。": "帖子按点赞数排序。",
    "ユーザーランキングは表示対象の投稿への合計いいね数を基準にしています。": "用户按可见帖子获得的点赞总数排序。",
    "診断ランキングは診断結果を共有した投稿数を基準にしています。": "测试按结果分享帖子的数量排序。",
    "投稿はいいね数、ユーザーは投稿への合計いいね数、診断は結果共有数を基準に順位を表示します。": "帖子按点赞数、用户按其帖子获得的点赞总数、测试按结果分享数排名。",
    "ランキング対象の投稿がありません。": "暂无可排名的帖子。",
    "ランキング対象のユーザーがいません。": "暂无可排名的用户。",
    "ランキング対象の診断がありません。": "暂无可排名的测试。",
    "診断": "性格测试", "診断を作る": "创建测试", "診断を外す": "移除测试",
    "遊び・エンタメ用の診断です。医療や病気の判定には使わないでください。": "此测试仅供娱乐，请勿用于评估健康或疾病。",
    "診断タイトル": "测试标题", "診断の説明（任意）": "测试说明（可选）", "みんなで遊べる診断": "大家都能玩的测试",
    "診断結果": "测试结果", "結果を追加": "添加结果", "結果名": "结果名称", "結果を削除": "删除结果", "結果の説明": "结果说明",
    "質問": "问题", "質問を追加": "添加问题", "質問を削除": "删除问题", "回答の選択肢": "回答选项", "この回答が示す結果": "此回答对应的结果",
    "問": "题", "あなたの診断結果": "你的测试结果", "結果を共有するにはログインしてください。": "请登录后分享结果。",
    "診断結果を投稿しました。": "已将结果分享到帖子。", "診断結果を投稿できませんでした。": "无法将结果分享到帖子。",
    "投稿中…": "分享中…", "結果を投稿で共有": "将结果分享到帖子", "もう一度遊ぶ": "再玩一次",
    "この投稿者の結果": "发帖者的结果", "診断をやってみる": "开始测试",
    "診断を探す": "发现测试", "診断を検索": "搜索测试", "診断がありません。": "还没有测试。", "該当する診断がありません。": "没有匹配的测试。", "診断を読み込めませんでした。": "无法加载测试。",
    "オリジナルの診断を作って投稿し、ほかのユーザーは回答して結果をシェアしたり、診断結果の投稿から再度遊んだりできます。": "可以从帖子中参与测试，也可以在测试列表中查找并直接游玩。搜索也能找到测试，结果可分享到帖子。",
    "投票・クイズ": "投票或问答", "投稿形式": "帖子类型", "なし": "无", "投票": "投票", "クイズ": "问答",
    "投稿に投票を付け、回答後に結果を確認できます。クイズでは複数の正解、正解・惜しい・不正解の判定、選択肢ごとのメッセージや解説を設定できます。": "可以在帖子中添加投票，并在回答后查看结果。问答支持多个正确答案、正确／接近正确／错误判定，以及每个选项的提示和解析。",
    "選択肢": "选项", "選択肢を削除": "删除选项", "判定": "判定", "正解": "正确", "惜しい": "接近正确", "不正解": "错误",
    "回答後のメッセージ（任意）": "回答后的提示（可选）", "選択肢を追加": "添加选项",
    "複数の選択肢を回答できるようにする": "允许多选", "回答後の解説（任意）": "回答后的解析（可选）",
    "正解は複数設定できます。複数正解の場合は複数選択となり、判定は回答後に表示されます。": "可以设置多个正确答案；多个正确答案时需要多选，提交回答后显示判定。",
    "回答後に投票結果を表示します。": "提交回答后显示投票结果。", "回答": "个回答",
    "回答するにはAppleかGoogleでログインしてください。": "请使用 Apple 或 Google 登录后回答。",
    "回答を保存できませんでした。": "无法保存回答。", "回答を選択してください。": "请选择答案。",
    "回答を送信中…": "正在提交…", "回答する": "提交回答", "解説": "解析",
    "複数選択できます。": "可以选择多个选项。", "投票の入力内容を確認してください。": "请检查投票选项和设置。",
    "投稿できませんでした。もう一度試してください。": "无法发布帖子，请重试。",
    "おすすめ": "为你推荐",
    "新着順": "最新",
    "タイムラインの表示順": "时间线排序",
    "いいね・ブックマーク・自分の投稿を手がかりに、話題の近い投稿を優先します。": "根据你点赞、收藏和发帖的主题进行推荐。",
    "コミュニティ、メンバー情報、すべての投稿が削除されます。この操作は取り消せません。": "社区、成员信息和所有帖子都会被删除，此操作无法撤销。",
    "コミュニティ": "社区",
    "誰でも閲覧・参加できます。投稿するには参加が必要です。": "任何人都可以查看和加入。加入后才能发帖。",
    "コミュニティを利用するにはAppleかGoogleでログインしてください。": "请使用 Apple 或 Google 登录后参与社区。",
    "コミュニティを読み込めませんでした。": "无法加载社区。",
    "コミュニティの操作に失敗しました。再読み込みして参加状態を確認してください。": "操作失败，请刷新后确认参与状态。",
    "コミュニティ名は1〜40文字、説明は160文字以内で入力してください。": "社区名称须为1至40个字符，说明不超过160个字符。",
    "コミュニティを検索": "搜索社区",
    "参加中のみ": "仅显示已加入的社区",
    "参加中": "已加入",
    "コミュニティを作成": "创建社区",
    "コミュニティを編集": "编辑社区",
    "コミュニティを削除": "删除社区",
    "コミュニティがありません。": "没有社区。",
    "コミュニティが見つかりません。": "找不到社区。",
    "参加する": "加入",
    "退出する": "退出",
    "参加が制限されています。管理者またはモデレーターに確認してください。": "你的参与受到限制，请联系社区所有者或版主。",
    "管理者": "所有者",
    "モデレーター": "版主",
    "モデレーターにする": "设为版主",
    "モデレーターを解除": "取消版主",
    "参加制限中": "参与受限",
    "参加を復帰": "恢复参与",
    "メンバーを除外": "移除成员",
    "コミュニティに投稿": "发布到社区",
    "コミュニティの投稿": "社区帖子",
    "固定された投稿": "置顶帖子",
    "投稿を固定": "置顶帖子",
    "固定を解除": "取消置顶",
    "投稿を削除": "删除帖子",
    "コミュニティ名（1〜40文字）": "社区名称（1至40个字符）",
    "メンバーを除外しますか？": "要移除这名成员吗？",
    "投稿を削除しますか？": "要删除这篇帖子吗？",
    "コミュニティを削除しますか？": "要删除这个社区吗？",
    "管理者またはモデレーターが復帰させるまで、このメンバーは参加・投稿できなくなります。": "在所有者或版主恢复之前，此成员无法加入或发帖。",
    "この操作は取り消せません。": "此操作无法撤销。",
    "実行する": "确认",
    "更新": "刷新",
    "公開": "公开",
    "非公開": "私密",
    "公開リスト": "公开列表",
    "リストを公開": "公开列表",
    "非公開にする": "设为私密",
    "公開ページを見る": "查看公开页面",
    "共有リンク": "分享链接",
    "共有リンクをコピー": "复制分享链接",
    "コピーしました": "已复制",
    "共有リンクをコピーできませんでした。": "无法复制分享链接。",
    "公開リストを探す": "发现公开列表",
    "リスト名で検索": "按列表名称搜索",
    "公開リストがありません。": "没有公开列表。",
    "公開リストを読み込めませんでした。": "无法加载公开列表。",
    "このリストは公開されていないか、削除されています。": "此列表未公开或已删除。",
    "公開するにはAppleかGoogleでログインしてください。": "请使用 Apple 或 Google 登录后公开列表。",
    "リストは初期状態では非公開です。公開すると共有リンクから誰でも閲覧できます。": "列表默认是私密的。公开后，任何人都可以通过分享链接查看。",
    "リスト": "列表",
    "リストを作成": "创建列表",
    "リストを編集": "编辑列表",
    "リストを削除": "删除列表",
    "リストを削除しますか？": "要删除这个列表吗？",
    "リストとメンバー設定が削除されます。投稿は削除されません。": "列表和成员设置会被删除，帖子不会被删除。",
    "リスト名（1〜40文字）": "列表名称（1至40个字符）",
    "説明（160文字まで）": "说明（最多160个字符）",
    "メンバー": "成员",
    "メンバー一覧": "成员列表",
    "ユーザーを検索": "搜索用户",
    "ユーザー名・表示名": "用户名或显示名称",
    "追加": "添加",
    "リストから削除": "从列表中移除",
    "リストの投稿": "列表帖子",
    "まだリストがありません。": "还没有列表。",
    "ユーザーを追加すると投稿が表示されます。": "添加用户后即可查看其帖子。",
    "リストはこの端末に保存されます。": "列表保存在此设备上。",
    "リストは自分だけに表示され、端末間で共有されます。": "列表仅自己可见，并会在设备间同步。",
    "リストが見つかりません。": "找不到列表。",
    "リストを読み込めませんでした。": "无法加载列表。",
    "リストを保存できませんでした。": "无法保存列表。",
    "リストを保存・読み込みできませんでした。": "无法保存或加载列表。",
    "ユーザーを検索できませんでした。": "无法搜索用户。",
    "ユーザーが見つかりません。": "找不到用户。",
    "リスト名は1〜40文字、説明は160文字以内で入力してください。": "列表名称须为1至40个字符，说明不超过160个字符。",
    "ミュート": "静音",
    "ミュートを解除": "取消静音",
    "ブロック": "屏蔽",
    "ブロックを解除": "取消屏蔽",
    "ミュート・ブロック中のアカウント": "已静音和屏蔽的账号",
    "登録されたアカウントはありません。": "没有已静音或屏蔽的账号。",
    "解除": "取消",
    "設定を読み込めませんでした。": "无法加载设置。",
    "設定を保存できませんでした。": "无法保存设置。",
    "自分をミュート・ブロックできません。": "不能静音或屏蔽自己。",
    "PDFとして出力": "导出为 PDF",
    "PDFを開けませんでした。": "无法打开 PDF 预览。",
    "返信": "回复",
    "返信する": "回复",
    "返信本文": "回复内容",
    "返信先": "回复对象",
    "返信先の投稿": "查看原帖",
    "返信するにはログインしてください。": "请登录后回复。",
    "返信を保存できませんでした。": "无法保存回复。",
    "返信は1〜70文字で入力してください。": "回复须为1至70个字符。",
    "まだ返信がありません。": "还没有回复。",
    "送信中…": "发送中…",
    "{name}さんがいいねしました。": "{name}赞了你的帖子。",
    "1人があなたの投稿にいいねしました。": "1人赞了你的帖子。",
    "{count}人があなたの投稿にいいねしました。": "{count}人赞了你的帖子。",
    "通知": "通知",
    "未読の通知": "未读通知",
    "自分の投稿へのいいねをお知らせします。": "你的帖子获赞会显示在这里。",
    "通知を見るにはログインしてください。": "请登录后查看通知。",
    "開発モードでは通知は届きません。": "开发模式下不会收到通知。",
    "通知を読み込めませんでした。": "无法加载通知。",
    "通知を既読にできませんでした。": "无法将通知标记为已读。",
    "すべて既読にする": "全部标为已读",
    "まだ通知がありません。": "还没有通知。",
    "さんがあなたの投稿にいいねしました。": "赞了你的帖子。",
    "もっと見る": "加载更多",
    "ブックマークはアカウントに保存され、端末間で共有されます。": "书签会保存到账号并在设备间同步。",
    "開発モードのブックマークはこの端末に保存されます。": "开发模式的书签保存在此设备上。",
    "ブックマーク": "书签",
    "ブックマークに追加": "添加书签",
    "ブックマークを解除": "取消书签",
    "ブックマークするにはログインしてください。": "请登录后添加书签。",
    "ブックマークを保存できませんでした。": "无法保存书签。",
    "ブックマークを読み込めませんでした。": "无法加载书签。",
    "まだブックマークがありません。": "还没有书签。",
    "ブックマークはこの端末に保存されます。": "书签保存在此设备上。",
    "ナビゲーション": "导航",
    "サイドナビゲーション": "侧边导航",
    "左側サイドバー（デスクトップ）": "桌面左侧边栏",
    "ボトムバー（デスクトップ）": "桌面底部栏",
    "デスクトップでは左側サイドバーを使用します。モバイルではボトムバーを使用します。": "桌面使用左侧边栏，移动端使用底部栏。",
    "ボトムバー": "底部栏",
    "ボトムバーの文字を表示": "显示底部栏文字",
    "ホーム": "首页",
    "検索": "搜索",
    "キーワードで投稿を検索": "按关键词搜索帖子",
    "ユーザー名や本文のキーワードで投稿を探せます。": "可按用户名或帖子关键词搜索。",
    "該当する投稿がありません。": "没有匹配的帖子。",
    "投稿": "帖子",
    "自分": "我的",
    "設定": "设置",
    "あなた": "你",
    "あ": "我",
    "ログイン": "登录",
    "閉じる": "关闭",
    "いいね": "赞",
    "ライト": "浅色",
    "ダーク": "深色",
    "ダークブルー": "深蓝",
    "ミント": "薄荷",
    "システム": "跟随系统",
    "ふぁぼ": "收藏",
    "デフォルト": "默认",
    "高評価": "赞成",
    "賛成": "支持",
    "外観": "外观",
    "テーマ": "主题",
    "言語": "语言",
    "日付表示": "日期显示",
    "相対表示": "相对显示",
    "月日と時刻": "月日和时间",
    "年月日と時刻": "完整日期和时间",
    "今日": "今天",
    "機能ガイド": "功能指南",
    "Irukaの主要機能をまとめています。": "这里汇总了 Iruka 的主要功能。",
    "70文字までの投稿を作成し、返信・いいね・ブックマークを使えます。": "可以创建不超过70字的帖子，并使用回复、点赞和书签。",
    "公開コミュニティを作成・検索・参加できます。作成者とモデレーターはメンバーや投稿を管理し、投稿を固定できます。": "可以创建、搜索和加入公开社区。所有者和版主可以管理成员与帖子，并置顶帖子。",
    "ユーザーをリストに追加すると、そのユーザーの投稿をまとめて確認できます。公開すると共有リンクで誰でも閲覧できます。": "将用户加入列表即可集中查看其帖子。公开列表后，任何人都能通过分享链接查看。",
    "自分の投稿へのいいね通知を確認し、既読にできます。": "可以查看自己帖子收到的赞，并标记为已读。",
    "表示名、ユーザー名、自己紹介、プロフィール画像を編集できます。": "可以编辑显示名称、用户名、简介和头像。",
    "テーマ、言語、いいねアイコン、日付表示などを変更できます。": "可以更改主题、语言、点赞图标和日期显示等设置。",
    "アカウントなしで試せます。データはこの端末に保存され、30日後に削除されます。": "无需账号即可试用。数据保存在此设备上，并在30天后删除。",
    "ミュートしたアカウントを非表示にし、ブロックしたアカウントとの関係を制限できます。": "可以隐藏已静音的账号，并限制与已屏蔽账号的互动。",
    "投稿詳細から投稿をPDFとして保存・共有できます。": "可以从帖子详情中将帖子保存或分享为 PDF。",
    "設定からいつでもこのガイドを開けます。": "随时可以从设置打开此指南。",
    "いいねアイコン": "点赞图标",
    "アイコン": "图标",
    "システムを選ぶと端末の外観設定に合わせて切り替わります。": "选择跟随系统后会匹配设备的外观设置。",
    "いいねの表示に使うアイコンを選べます。": "选择用于显示点赞的图标。",
    "イルカ": "Iruka",
    "今の気持ちを、70字まで。": "分享此刻的心情，最多70字。",
    "新しい投稿": "新帖子",
    "投稿する": "发布",
    "投稿を作成": "创建帖子",
    "投稿本文": "帖子内容",
    "メインナビゲーション": "主导航",
    "いまどうしてる？": "有什么新鲜事？",
    "プロフィール": "个人资料",
    "今週の投稿": "本周帖子",
    "プロフィールを見る・編集": "查看或编辑个人资料",
    "自分の投稿": "我的帖子",
    "ログインすると、この端末を超えて自分の投稿が見られます。": "登录后即可在多个设备查看自己的帖子。",
    "まだ投稿がありません": "还没有帖子",
    "まだ投稿がありません。": "还没有帖子。",
    "70字以内で、いまの気持ちを残しましょう。": "用不超过70字记录此刻的心情。",
    "ログアウト": "退出登录",
    "ログアウトしますか？": "要退出登录吗？",
    "この端末からサインアウトします。もう一度ログインできます。": "将退出此设备的登录，之后可以再次登录。",
    "ゲストでログイン": "以访客身份继续",
    "アカウント登録なしで試せます。データはこの端末にだけ保存され、30日で削除されます。": "无需注册账号即可试用。数据仅保存在此设备上，并在30天后删除。",
    "ゲスト": "访客",
    "ゲストモード・このブラウザに保存": "访客模式 · 保存在此浏览器",
    "ゲストモードのブックマークはこの端末に保存されます。": "访客模式的书签保存在此设备上。",
    "ゲストモードでは通知は届きません。": "访客模式下不会收到通知。",
    "ゲストの投稿を新しいアカウントに引き継ぎました": "已将访客帖子转移到新账号。",
    "ゲストのデータは保持期限（30日）を過ぎたため、削除されました。": "访客数据已超过30天保存期限并删除。",
    "プロフィールを見る": "查看个人资料",
    "投稿時刻": "发布时间",
    "文字数": "字数",
    "いいねを取り消す": "取消点赞",
    "いいね数": "点赞数",
    "読み込み中…": "加载中…",
    "プロフィールを編集": "编辑个人资料",
    "プロフィール編集": "编辑个人资料",
    "プロフィールが見つかりません。": "找不到个人资料。",
    "再読み込み": "重试",
    "プロフィールを読み込めませんでした。": "无法加载个人资料。",
    "表示名（1〜40文字）": "显示名称（1至40个字符）",
    "表示名": "显示名称",
    "ユーザー名（英数字と_、3〜25文字）": "用户名（字母、数字和下划线，3至25个字符）",
    "ユーザー名": "用户名",
    "自己紹介（160文字まで）": "简介（最多160个字符）",
    "プロフィール画像URL": "头像图片 URL",
    "プロフィール画像": "头像",
    "画像を変更": "更换图片",
    "画像を削除": "删除图片",
    "アップロード中…": "上传中…",
    "画像をアップロードできませんでした。": "无法上传图片。",
    "画像ファイルを選んでください。": "请选择图片文件。",
    "画像は10MBまでです。": "图片不能超过10 MB。",
    "JPEGやPNGの画像を登録できます。": "可上传 JPEG 或 PNG 图片。",
    "HTTPSの画像URL。空欄にすると画像を解除します。": "HTTPS 图片 URL。留空即可移除图片。",
    "キャンセル": "取消",
    "保存中…": "保存中…",
    "保存": "保存",
    "保存する": "保存",
    "保存できませんでした。入力内容とユーザー名の重複を確認してください。": "无法保存，请检查内容和用户名是否重复。",
    "ログインしてはじめる": "登录并开始",
    "GoogleかAppleで入ると、自分の投稿が残ります。": "使用 Google 或 Apple 登录即可保留自己的帖子。",
    "Googleで続ける": "继续使用 Google",
    "Appleで続ける": "继续使用 Apple",
    "開発用にログインをスキップ": "开发模式跳过登录",
    "スキップ中のデータはこの端末内に保存されます。": "开发数据保存在此设备上。",
    "ログインできませんでした": "无法登录",
    "ログインに失敗しました": "登录失败",
    "ログイン用のURLが不正です": "登录 URL 无效。",
    "認証コードを受け取れませんでした": "无法接收验证码。",
    "URLが不正です": "URL 无效。",
    "ログインが時間切れになりました": "登录超时。",
    "ログインをキャンセルしました": "已取消登录。",
    "いいねするにはAppleかGoogleでログインしてください。": "请使用 Apple 或 Google 登录后点赞。",
    "いいねを保存できませんでした。もう一度試してください。": "无法保存点赞，请重试。",
    "投稿またはいいねを読み込めませんでした。": "无法加载帖子或点赞。",
    "ユーザー": "用户",
    "表示名・ユーザー名・自己紹介・画像URLを確認してください。": "请检查显示名称、用户名、简介和图片 URL。",
    "開発ユーザーが一致しません。": "开发用户不匹配。",
    "プロフィールを保存できませんでした。": "无法保存个人资料。",
    "ログイン情報が見つかりません。もう一度試してください。": "找不到登录信息，请重试。",
    "ポップアップがブロックされました。許可してからもう一度試してください。": "弹出窗口被阻止，请允许后重试。",
    "投稿は1〜70文字で入力してください。": "帖子须为1至70个字符。",
    "投稿できませんでした": "无法发布帖子。",
    "投稿が見つかりません。": "找不到帖子。",
    "いいねするにはログインしてください。": "请登录后点赞。",
    "いいねを保存できませんでした。": "无法保存点赞。",
    "表示名は1〜40文字で入力してください。": "显示名称须为1至40个字符。",
    "ユーザー名は小文字の英数字と_で3〜25文字にしてください。": "用户名须为3至25个小写字母、数字或下划线。",
    "自己紹介は160文字以内で入力してください。": "简介不能超过160个字符。",
    "画像にはHTTPSのURLを指定してください。": "图片须使用 HTTPS URL。",
    "画像のURLを確認してください。": "请检查图片 URL。",
    "このユーザー名は既に使われています。": "此用户名已被占用。",
    "プロフィールを保存できませんでした。もう一度試してください。": "无法保存个人资料，请重试。",
    "ログインしています…": "正在登录…",
    "ログイン中…": "登录中…",
    "タイムラインを読み込めませんでした。": "无法加载时间线。",
    "投稿できませんでした。もう一度試してください。": "无法发布帖子，请重试。",
    "投稿するには、GoogleかAppleで入ってください。": "请使用 Google 或 Apple 登录后发帖。",
    "開発モード・このブラウザに保存": "开发模式 · 保存在此浏览器",
    "編集する": "编辑",
    "1〜40文字": "1至40个字符",
    "小文字の英数字と_、3〜25文字": "小写字母、数字和下划线，3至25个字符",
    "3〜25文字": "3至25个字符",
    "小文字の英数字と_": "小写字母、数字和下划线",
    "確認中…": "检查中…",
    "利用できるユーザー名です。": "此用户名可用。",
    "自己紹介": "简介",
    "保存できませんでした。": "无法保存。",
    "戻る": "返回",
    "今朝": "今天",
    "昨日": "昨天",
    "Oops! Page not found": "页面未找到。",
    "Return to Home": "返回首页",
    "文字": "字符",
    "字": "字",
    "投稿数": "帖子数",
    " 投稿": " 帖子",
    "文字まで": "字符上限",
    "開発セッションではありません。": "不是开发会话。",
    "アカウント": "账号",
    "メールアドレス": "电子邮件",
    "ログインしていません。": "尚未登录。",
    "未設定": "未设置",
    "アカウントを削除": "删除账号",
    "アカウントを削除しますか？": "要删除此账号吗？",
    "投稿、プロフィール、いいね、ブックマーク、通知が削除されます。この操作は取り消せません。": "你的帖子、个人资料、点赞、书签和通知都会被删除，此操作无法撤销。",
    "削除中…": "删除中…",
    "削除する": "删除",
    "アカウントを削除できませんでした。": "无法删除账号。",
    "Today": "今天",
    "Yesterday": "昨天",
]
private let simplifiedToTraditional: [(String, String)] = [
    ("社区", "社群"), ("帖子", "貼文"), ("搜索", "搜尋"), ("点赞", "按讚"), ("发布", "發佈"),
    ("回复", "回覆"), ("重复", "重複"), ("设置", "設定"), ("默认", "預設"), ("简体中文", "簡體中文"),
    ("繁体中文", "繁體中文"), ("个人资料", "個人資料"), ("用户名", "使用者名稱"), ("用户", "使用者"),
    ("显示名称", "顯示名稱"), ("弹出窗口", "彈出視窗"), ("账号", "帳號"), ("账户", "帳戶"),
    ("浅色", "淺色"), ("深色", "深色"), ("关闭", "關閉"), ("登录", "登入"), ("导出", "匯出"),
    ("简体", "簡體"), ("繁体", "繁體"), ("选择", "選擇"), ("切换", "切換"), ("头像", "頭像"),
    ("加载", "載入"), ("创建", "建立"), ("删除", "刪除"), ("无法", "無法"), ("允许", "允許"),
    ("没", "沒"), ("无", "無"), ("个", "個"), ("联", "聯"), ("员", "員"), ("权", "權"),
    ("发", "發"), ("请", "請"), ("参", "參"), ("进", "進"), ("确", "確"), ("认", "認"),
    ("开", "開"), ("页", "頁"), ("链", "鏈"), ("制", "製"), ("现", "現"), ("设", "設"),
    ("语", "語"), ("显", "顯"), ("时", "時"), ("间", "間"), ("户", "戶"), ("账", "帳"),
    ("号", "號"), ("邮", "郵"), ("码", "碼"), ("图", "圖"), ("标", "標"), ("变", "變"),
    ("换", "換"), ("传", "傳"), ("续", "續"), ("询", "詢"), ("错", "錯"), ("误", "誤"),
    ("过", "過"), ("这", "這"), ("动", "動"), ("态", "態"), ("级", "級"), ("数", "數"),
    ("据", "據"), ("仅", "僅"), ("访", "訪"), ("试", "試"), ("验", "驗"), ("备", "備"),
    ("储", "儲"), ("题", "題"), ("览", "覽"), ("阅", "閱"), ("读", "讀"), ("记", "記"),
    ("录", "錄"), ("销", "銷"), ("顶", "頂"), ("帮", "幫"), ("围", "圍"), ("网", "網"),
    ("络", "絡"), ("应", "應"), ("问", "問"), ("尝", "嘗"), ("并", "並"), ("对", "對"),
    ("于", "於"), ("将", "將"), ("会", "會"), ("来", "來"), ("写", "寫"), ("见", "見"),
    ("后", "後"), ("总", "總"), ("签", "簽"), ("类", "類"), ("别", "別"), ("简", "簡"),
    ("体", "體"), ("专", "專"), ("导", "導"), ("档", "檔"), ("为", "為"), ("还", "還"),
    ("从", "從"), ("迁", "遷"), ("转", "轉"), ("资", "資"), ("电", "電"), ("侧", "側"),
    ("划", "劃"), ("称", "稱"), ("检", "檢"), ("选", "選"), ("择", "擇"), ("线", "線"),
    ("赞", "讚"), ("贴", "貼"), ("浅", "淺"), ("头", "頭"), ("关", "關"), ("闭", "閉"),
    ("许", "許"), ("议", "議"), ("复", "復"),
    ("测", "測"), ("结", "結"), ("创", "創"), ("娱", "娛"), ("乐", "樂"), ("说", "說"), ("项", "項"),
]
private func traditionalize(_ value: String) -> String {
    simplifiedToTraditional.reduce(value) { result, pair in
        result.replacingOccurrences(of: pair.0, with: pair.1)
    }
}
private let japaneseFormats: [String: String] = ["character_count": "%d字、上限%d字", "characters": "%d字", "like_count": "%d件", "post_count": "%d 投稿", "today_time": "今朝 %@", "yesterday_time": "昨日 %@"]
private let englishFormats: [String: String] = ["character_count": "%d characters, maximum %d", "characters": "%d characters", "like_count": "%d likes", "post_count": "%d posts", "today_time": "Today %@", "yesterday_time": "Yesterday %@"]
private let koreanFormats: [String: String] = ["character_count": "최대 %d자 중 %d자", "characters": "%d자", "like_count": "좋아요 %d개", "post_count": "게시물 %d개", "today_time": "오늘 %@", "yesterday_time": "어제 %@"]
private let simplifiedChineseFormats: [String: String] = ["character_count": "%d 个字符，最多 %d 个", "characters": "%d 个字符", "like_count": "%d 个赞", "post_count": "%d 个帖子", "today_time": "今天 %@", "yesterday_time": "昨天 %@"]
private let traditionalChineseFormats: [String: String] = ["character_count": "%d 個字元，上限 %d 個", "characters": "%d 個字元", "like_count": "%d 個讚", "post_count": "%d 則貼文", "today_time": "今天 %@", "yesterday_time": "昨天 %@"]

func L(_ message: String, _ arguments: CVarArg...) -> String {
    let language = AppLanguage.current
    let translated: String
    let formats: [String: String]
    switch language {
    case .en: formats = englishFormats
    case .ko: formats = koreanFormats
    case .zhHans: formats = simplifiedChineseFormats
    case .zhHant: formats = traditionalChineseFormats
    case .ja: formats = japaneseFormats
    }
    if let format = formats[message] {
        translated = format
    } else if language == .ko {
        if message.hasPrefix("ログインに失敗しました（") {
            translated = message.replacingOccurrences(of: "ログインに失敗しました（", with: "로그인 실패(").replacingOccurrences(of: "）", with: ")")
        } else {
            translated = koreanMessages[message] ?? koreanExtraMessages[message] ?? englishMessages[message] ?? message
        }
    } else if language == .en {
        if message.hasPrefix("ログインに失敗しました（") {
            translated = message.replacingOccurrences(of: "ログインに失敗しました（", with: "Sign-in failed (").replacingOccurrences(of: "）", with: ")")
        } else {
            translated = englishMessages[message] ?? message
        }
    } else if language == .zhHans {
        if message.hasPrefix("ログインに失敗しました（") {
            translated = message.replacingOccurrences(of: "ログインに失敗しました（", with: "登录失败(").replacingOccurrences(of: "）", with: ")")
        } else {
            translated = simplifiedChineseMessages[message] ?? englishMessages[message] ?? message
        }
    } else if language == .zhHant {
        if message.hasPrefix("ログインに失敗しました（") {
            translated = message.replacingOccurrences(of: "ログインに失敗しました（", with: "登入失敗(").replacingOccurrences(of: "）", with: ")")
        } else {
            translated = traditionalize(simplifiedChineseMessages[message] ?? englishMessages[message] ?? message)
        }
    } else {
        translated = message
    }
    return arguments.isEmpty ? translated : String(format: translated, locale: AppLanguage.locale, arguments: arguments)
}

struct AppLanguageModifier: ViewModifier {
    @AppStorage("iruka-language") private var language = AppLanguage.ja.rawValue
    func body(content: Content) -> some View {
        content.environment(\.locale, Locale(identifier: language))
    }
}
